version: "2"
run:
  go: "1.23"
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - containedctx
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - ireturn
    - maintidx
    - nestif
    - nolintlint
    - nonamedreturns
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - varnamelen
    - wastedassign
    - wrapcheck
  settings:
    funlen:
      lines: 110
      statements: 60
    lll:
      line-length: 150
    mnd:
      ignored-numbers:
        - "30"
        - "20"
        - "5"
        - "4"
        - "3"
        - "2"
        - "10"
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: bool-literal-in-expr
        - name: constant-logical-expr
    wsl:
      force-err-cuddling: false
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - testpackage
        path: _test\.go
      - linters:
          - lll
        source: '^//\s*\+kubebuilder:'
      - linters:
          - dupl
          - wrapcheck
        path: _webhook\.go
      - linters:
          - revive
        text: var-naming
      - linters:
          - staticcheck
        text: ST1003
      - linters:
          - gosec
        text: G114
      - linters:
          - revive
        path: pkg/rke2
        text: unexported-return
      - linters:
          - revive
        text: "package-comments: should have a package comment"
    paths:
      - zz_generated.*\.go$
      - conversion\.go
      - vendored_openapi\.go$
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - blank
        - dot
        - default
        - prefix(sigs.k8s.io/cluster-api)
        - prefix(github.com/rancher/cluster-api-provider-rke2)
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/rancher/cluster-api-provider-rke2
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - conversion\.go
      - vendored_openapi\.go$
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
