//go:build !ignore_autogenerated_rke2_bootstrap
// +build !ignore_autogenerated_rke2_bootstrap

/*
Copyright 2023 SUSE.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/rancher-sandbox/cluster-api-provider-rke2/bootstrap/api/v1alpha2"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalUserData)(nil), (*v1alpha2.AdditionalUserData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdditionalUserData_To_v1alpha2_AdditionalUserData(a.(*AdditionalUserData), b.(*v1alpha2.AdditionalUserData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AdditionalUserData)(nil), (*AdditionalUserData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AdditionalUserData_To_v1alpha1_AdditionalUserData(a.(*v1alpha2.AdditionalUserData), b.(*AdditionalUserData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentConfig)(nil), (*v1alpha2.ComponentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentConfig_To_v1alpha2_ComponentConfig(a.(*ComponentConfig), b.(*v1alpha2.ComponentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ComponentConfig)(nil), (*ComponentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ComponentConfig_To_v1alpha1_ComponentConfig(a.(*v1alpha2.ComponentConfig), b.(*ComponentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*v1alpha2.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_File_To_v1alpha2_File(a.(*File), b.(*v1alpha2.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_File_To_v1alpha1_File(a.(*v1alpha2.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSource)(nil), (*v1alpha2.FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileSource_To_v1alpha2_FileSource(a.(*FileSource), b.(*v1alpha2.FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.FileSource)(nil), (*FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_FileSource_To_v1alpha1_FileSource(a.(*v1alpha2.FileSource), b.(*FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Mirror)(nil), (*v1alpha2.Mirror)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Mirror_To_v1alpha2_Mirror(a.(*Mirror), b.(*v1alpha2.Mirror), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Mirror)(nil), (*Mirror)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Mirror_To_v1alpha1_Mirror(a.(*v1alpha2.Mirror), b.(*Mirror), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NTP)(nil), (*v1alpha2.NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NTP_To_v1alpha2_NTP(a.(*NTP), b.(*v1alpha2.NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NTP)(nil), (*NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NTP_To_v1alpha1_NTP(a.(*v1alpha2.NTP), b.(*NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2AgentConfig)(nil), (*v1alpha2.RKE2AgentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2AgentConfig_To_v1alpha2_RKE2AgentConfig(a.(*RKE2AgentConfig), b.(*v1alpha2.RKE2AgentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2AgentConfig)(nil), (*RKE2AgentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2AgentConfig_To_v1alpha1_RKE2AgentConfig(a.(*v1alpha2.RKE2AgentConfig), b.(*RKE2AgentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2Config)(nil), (*v1alpha2.RKE2Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2Config_To_v1alpha2_RKE2Config(a.(*RKE2Config), b.(*v1alpha2.RKE2Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2Config)(nil), (*RKE2Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2Config_To_v1alpha1_RKE2Config(a.(*v1alpha2.RKE2Config), b.(*RKE2Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigList)(nil), (*v1alpha2.RKE2ConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigList_To_v1alpha2_RKE2ConfigList(a.(*RKE2ConfigList), b.(*v1alpha2.RKE2ConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigList)(nil), (*RKE2ConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigList_To_v1alpha1_RKE2ConfigList(a.(*v1alpha2.RKE2ConfigList), b.(*RKE2ConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigSpec)(nil), (*v1alpha2.RKE2ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec(a.(*RKE2ConfigSpec), b.(*v1alpha2.RKE2ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigSpec)(nil), (*RKE2ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec(a.(*v1alpha2.RKE2ConfigSpec), b.(*RKE2ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigStatus)(nil), (*v1alpha2.RKE2ConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigStatus_To_v1alpha2_RKE2ConfigStatus(a.(*RKE2ConfigStatus), b.(*v1alpha2.RKE2ConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigStatus)(nil), (*RKE2ConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigStatus_To_v1alpha1_RKE2ConfigStatus(a.(*v1alpha2.RKE2ConfigStatus), b.(*RKE2ConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplate)(nil), (*v1alpha2.RKE2ConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigTemplate_To_v1alpha2_RKE2ConfigTemplate(a.(*RKE2ConfigTemplate), b.(*v1alpha2.RKE2ConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigTemplate)(nil), (*RKE2ConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigTemplate_To_v1alpha1_RKE2ConfigTemplate(a.(*v1alpha2.RKE2ConfigTemplate), b.(*RKE2ConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateList)(nil), (*v1alpha2.RKE2ConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigTemplateList_To_v1alpha2_RKE2ConfigTemplateList(a.(*RKE2ConfigTemplateList), b.(*v1alpha2.RKE2ConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigTemplateList)(nil), (*RKE2ConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigTemplateList_To_v1alpha1_RKE2ConfigTemplateList(a.(*v1alpha2.RKE2ConfigTemplateList), b.(*RKE2ConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateResource)(nil), (*v1alpha2.RKE2ConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigTemplateResource_To_v1alpha2_RKE2ConfigTemplateResource(a.(*RKE2ConfigTemplateResource), b.(*v1alpha2.RKE2ConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigTemplateResource)(nil), (*RKE2ConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigTemplateResource_To_v1alpha1_RKE2ConfigTemplateResource(a.(*v1alpha2.RKE2ConfigTemplateResource), b.(*RKE2ConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateSpec)(nil), (*v1alpha2.RKE2ConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RKE2ConfigTemplateSpec_To_v1alpha2_RKE2ConfigTemplateSpec(a.(*RKE2ConfigTemplateSpec), b.(*v1alpha2.RKE2ConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RKE2ConfigTemplateSpec)(nil), (*RKE2ConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RKE2ConfigTemplateSpec_To_v1alpha1_RKE2ConfigTemplateSpec(a.(*v1alpha2.RKE2ConfigTemplateSpec), b.(*RKE2ConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Registry)(nil), (*v1alpha2.Registry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Registry_To_v1alpha2_Registry(a.(*Registry), b.(*v1alpha2.Registry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Registry)(nil), (*Registry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Registry_To_v1alpha1_Registry(a.(*v1alpha2.Registry), b.(*Registry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegistryConfig)(nil), (*v1alpha2.RegistryConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegistryConfig_To_v1alpha2_RegistryConfig(a.(*RegistryConfig), b.(*v1alpha2.RegistryConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RegistryConfig)(nil), (*RegistryConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RegistryConfig_To_v1alpha1_RegistryConfig(a.(*v1alpha2.RegistryConfig), b.(*RegistryConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretFileSource)(nil), (*v1alpha2.SecretFileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretFileSource_To_v1alpha2_SecretFileSource(a.(*SecretFileSource), b.(*v1alpha2.SecretFileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.SecretFileSource)(nil), (*SecretFileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SecretFileSource_To_v1alpha1_SecretFileSource(a.(*v1alpha2.SecretFileSource), b.(*SecretFileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSConfig)(nil), (*v1alpha2.TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLSConfig_To_v1alpha2_TLSConfig(a.(*TLSConfig), b.(*v1alpha2.TLSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.TLSConfig)(nil), (*TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_TLSConfig_To_v1alpha1_TLSConfig(a.(*v1alpha2.TLSConfig), b.(*TLSConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdditionalUserData_To_v1alpha2_AdditionalUserData(in *AdditionalUserData, out *v1alpha2.AdditionalUserData, s conversion.Scope) error {
	out.Config = in.Config
	out.Strict = in.Strict
	return nil
}

// Convert_v1alpha1_AdditionalUserData_To_v1alpha2_AdditionalUserData is an autogenerated conversion function.
func Convert_v1alpha1_AdditionalUserData_To_v1alpha2_AdditionalUserData(in *AdditionalUserData, out *v1alpha2.AdditionalUserData, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdditionalUserData_To_v1alpha2_AdditionalUserData(in, out, s)
}

func autoConvert_v1alpha2_AdditionalUserData_To_v1alpha1_AdditionalUserData(in *v1alpha2.AdditionalUserData, out *AdditionalUserData, s conversion.Scope) error {
	out.Config = in.Config
	out.Strict = in.Strict
	return nil
}

// Convert_v1alpha2_AdditionalUserData_To_v1alpha1_AdditionalUserData is an autogenerated conversion function.
func Convert_v1alpha2_AdditionalUserData_To_v1alpha1_AdditionalUserData(in *v1alpha2.AdditionalUserData, out *AdditionalUserData, s conversion.Scope) error {
	return autoConvert_v1alpha2_AdditionalUserData_To_v1alpha1_AdditionalUserData(in, out, s)
}

func autoConvert_v1alpha1_ComponentConfig_To_v1alpha2_ComponentConfig(in *ComponentConfig, out *v1alpha2.ComponentConfig, s conversion.Scope) error {
	out.ExtraEnv = *(*map[string]string)(unsafe.Pointer(&in.ExtraEnv))
	out.ExtraArgs = *(*[]string)(unsafe.Pointer(&in.ExtraArgs))
	out.ExtraMounts = *(*map[string]string)(unsafe.Pointer(&in.ExtraMounts))
	out.OverrideImage = in.OverrideImage
	return nil
}

// Convert_v1alpha1_ComponentConfig_To_v1alpha2_ComponentConfig is an autogenerated conversion function.
func Convert_v1alpha1_ComponentConfig_To_v1alpha2_ComponentConfig(in *ComponentConfig, out *v1alpha2.ComponentConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentConfig_To_v1alpha2_ComponentConfig(in, out, s)
}

func autoConvert_v1alpha2_ComponentConfig_To_v1alpha1_ComponentConfig(in *v1alpha2.ComponentConfig, out *ComponentConfig, s conversion.Scope) error {
	out.ExtraEnv = *(*map[string]string)(unsafe.Pointer(&in.ExtraEnv))
	out.ExtraArgs = *(*[]string)(unsafe.Pointer(&in.ExtraArgs))
	out.ExtraMounts = *(*map[string]string)(unsafe.Pointer(&in.ExtraMounts))
	out.OverrideImage = in.OverrideImage
	return nil
}

// Convert_v1alpha2_ComponentConfig_To_v1alpha1_ComponentConfig is an autogenerated conversion function.
func Convert_v1alpha2_ComponentConfig_To_v1alpha1_ComponentConfig(in *v1alpha2.ComponentConfig, out *ComponentConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_ComponentConfig_To_v1alpha1_ComponentConfig(in, out, s)
}

func autoConvert_v1alpha1_File_To_v1alpha2_File(in *File, out *v1alpha2.File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = v1alpha2.Encoding(in.Encoding)
	out.Content = in.Content
	out.ContentFrom = (*v1alpha2.FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1alpha1_File_To_v1alpha2_File is an autogenerated conversion function.
func Convert_v1alpha1_File_To_v1alpha2_File(in *File, out *v1alpha2.File, s conversion.Scope) error {
	return autoConvert_v1alpha1_File_To_v1alpha2_File(in, out, s)
}

func autoConvert_v1alpha2_File_To_v1alpha1_File(in *v1alpha2.File, out *File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = Encoding(in.Encoding)
	out.Content = in.Content
	out.ContentFrom = (*FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1alpha2_File_To_v1alpha1_File is an autogenerated conversion function.
func Convert_v1alpha2_File_To_v1alpha1_File(in *v1alpha2.File, out *File, s conversion.Scope) error {
	return autoConvert_v1alpha2_File_To_v1alpha1_File(in, out, s)
}

func autoConvert_v1alpha1_FileSource_To_v1alpha2_FileSource(in *FileSource, out *v1alpha2.FileSource, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecretFileSource_To_v1alpha2_SecretFileSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_FileSource_To_v1alpha2_FileSource is an autogenerated conversion function.
func Convert_v1alpha1_FileSource_To_v1alpha2_FileSource(in *FileSource, out *v1alpha2.FileSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileSource_To_v1alpha2_FileSource(in, out, s)
}

func autoConvert_v1alpha2_FileSource_To_v1alpha1_FileSource(in *v1alpha2.FileSource, out *FileSource, s conversion.Scope) error {
	if err := Convert_v1alpha2_SecretFileSource_To_v1alpha1_SecretFileSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_FileSource_To_v1alpha1_FileSource is an autogenerated conversion function.
func Convert_v1alpha2_FileSource_To_v1alpha1_FileSource(in *v1alpha2.FileSource, out *FileSource, s conversion.Scope) error {
	return autoConvert_v1alpha2_FileSource_To_v1alpha1_FileSource(in, out, s)
}

func autoConvert_v1alpha1_Mirror_To_v1alpha2_Mirror(in *Mirror, out *v1alpha2.Mirror, s conversion.Scope) error {
	out.Endpoint = *(*[]string)(unsafe.Pointer(&in.Endpoint))
	out.Rewrite = *(*map[string]string)(unsafe.Pointer(&in.Rewrite))
	return nil
}

// Convert_v1alpha1_Mirror_To_v1alpha2_Mirror is an autogenerated conversion function.
func Convert_v1alpha1_Mirror_To_v1alpha2_Mirror(in *Mirror, out *v1alpha2.Mirror, s conversion.Scope) error {
	return autoConvert_v1alpha1_Mirror_To_v1alpha2_Mirror(in, out, s)
}

func autoConvert_v1alpha2_Mirror_To_v1alpha1_Mirror(in *v1alpha2.Mirror, out *Mirror, s conversion.Scope) error {
	out.Endpoint = *(*[]string)(unsafe.Pointer(&in.Endpoint))
	out.Rewrite = *(*map[string]string)(unsafe.Pointer(&in.Rewrite))
	return nil
}

// Convert_v1alpha2_Mirror_To_v1alpha1_Mirror is an autogenerated conversion function.
func Convert_v1alpha2_Mirror_To_v1alpha1_Mirror(in *v1alpha2.Mirror, out *Mirror, s conversion.Scope) error {
	return autoConvert_v1alpha2_Mirror_To_v1alpha1_Mirror(in, out, s)
}

func autoConvert_v1alpha1_NTP_To_v1alpha2_NTP(in *NTP, out *v1alpha2.NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_NTP_To_v1alpha2_NTP is an autogenerated conversion function.
func Convert_v1alpha1_NTP_To_v1alpha2_NTP(in *NTP, out *v1alpha2.NTP, s conversion.Scope) error {
	return autoConvert_v1alpha1_NTP_To_v1alpha2_NTP(in, out, s)
}

func autoConvert_v1alpha2_NTP_To_v1alpha1_NTP(in *v1alpha2.NTP, out *NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha2_NTP_To_v1alpha1_NTP is an autogenerated conversion function.
func Convert_v1alpha2_NTP_To_v1alpha1_NTP(in *v1alpha2.NTP, out *NTP, s conversion.Scope) error {
	return autoConvert_v1alpha2_NTP_To_v1alpha1_NTP(in, out, s)
}

func autoConvert_v1alpha1_RKE2AgentConfig_To_v1alpha2_RKE2AgentConfig(in *RKE2AgentConfig, out *v1alpha2.RKE2AgentConfig, s conversion.Scope) error {
	out.DataDir = in.DataDir
	out.NodeLabels = *(*[]string)(unsafe.Pointer(&in.NodeLabels))
	out.NodeAnnotations = *(*map[string]string)(unsafe.Pointer(&in.NodeAnnotations))
	out.NodeTaints = *(*[]string)(unsafe.Pointer(&in.NodeTaints))
	out.NodeNamePrefix = in.NodeNamePrefix
	out.NTP = (*v1alpha2.NTP)(unsafe.Pointer(in.NTP))
	out.ImageCredentialProviderConfigMap = (*v1.ObjectReference)(unsafe.Pointer(in.ImageCredentialProviderConfigMap))
	out.ContainerRuntimeEndpoint = in.ContainerRuntimeEndpoint
	out.Snapshotter = in.Snapshotter
	out.CISProfile = v1alpha2.CISProfile(in.CISProfile)
	out.ResolvConf = (*v1.ObjectReference)(unsafe.Pointer(in.ResolvConf))
	out.ProtectKernelDefaults = in.ProtectKernelDefaults
	out.SystemDefaultRegistry = in.SystemDefaultRegistry
	out.EnableContainerdSElinux = in.EnableContainerdSElinux
	out.KubeletPath = in.KubeletPath
	out.Kubelet = (*v1alpha2.ComponentConfig)(unsafe.Pointer(in.Kubelet))
	out.KubeProxy = (*v1alpha2.ComponentConfig)(unsafe.Pointer(in.KubeProxy))
	out.RuntimeImage = in.RuntimeImage
	out.LoadBalancerPort = in.LoadBalancerPort
	out.Version = in.Version
	out.AirGapped = in.AirGapped
	out.Format = v1alpha2.Format(in.Format)
	if err := Convert_v1alpha1_AdditionalUserData_To_v1alpha2_AdditionalUserData(&in.AdditionalUserData, &out.AdditionalUserData, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RKE2AgentConfig_To_v1alpha2_RKE2AgentConfig is an autogenerated conversion function.
func Convert_v1alpha1_RKE2AgentConfig_To_v1alpha2_RKE2AgentConfig(in *RKE2AgentConfig, out *v1alpha2.RKE2AgentConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2AgentConfig_To_v1alpha2_RKE2AgentConfig(in, out, s)
}

func autoConvert_v1alpha2_RKE2AgentConfig_To_v1alpha1_RKE2AgentConfig(in *v1alpha2.RKE2AgentConfig, out *RKE2AgentConfig, s conversion.Scope) error {
	out.DataDir = in.DataDir
	out.NodeLabels = *(*[]string)(unsafe.Pointer(&in.NodeLabels))
	out.NodeAnnotations = *(*map[string]string)(unsafe.Pointer(&in.NodeAnnotations))
	out.NodeTaints = *(*[]string)(unsafe.Pointer(&in.NodeTaints))
	out.NodeNamePrefix = in.NodeNamePrefix
	out.NTP = (*NTP)(unsafe.Pointer(in.NTP))
	out.ImageCredentialProviderConfigMap = (*v1.ObjectReference)(unsafe.Pointer(in.ImageCredentialProviderConfigMap))
	out.ContainerRuntimeEndpoint = in.ContainerRuntimeEndpoint
	out.Snapshotter = in.Snapshotter
	out.CISProfile = CISProfile(in.CISProfile)
	out.ResolvConf = (*v1.ObjectReference)(unsafe.Pointer(in.ResolvConf))
	out.ProtectKernelDefaults = in.ProtectKernelDefaults
	out.SystemDefaultRegistry = in.SystemDefaultRegistry
	out.EnableContainerdSElinux = in.EnableContainerdSElinux
	out.KubeletPath = in.KubeletPath
	out.Kubelet = (*ComponentConfig)(unsafe.Pointer(in.Kubelet))
	out.KubeProxy = (*ComponentConfig)(unsafe.Pointer(in.KubeProxy))
	out.RuntimeImage = in.RuntimeImage
	out.LoadBalancerPort = in.LoadBalancerPort
	out.Version = in.Version
	out.AirGapped = in.AirGapped
	out.Format = Format(in.Format)
	if err := Convert_v1alpha2_AdditionalUserData_To_v1alpha1_AdditionalUserData(&in.AdditionalUserData, &out.AdditionalUserData, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RKE2AgentConfig_To_v1alpha1_RKE2AgentConfig is an autogenerated conversion function.
func Convert_v1alpha2_RKE2AgentConfig_To_v1alpha1_RKE2AgentConfig(in *v1alpha2.RKE2AgentConfig, out *RKE2AgentConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2AgentConfig_To_v1alpha1_RKE2AgentConfig(in, out, s)
}

func autoConvert_v1alpha1_RKE2Config_To_v1alpha2_RKE2Config(in *RKE2Config, out *v1alpha2.RKE2Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RKE2ConfigStatus_To_v1alpha2_RKE2ConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RKE2Config_To_v1alpha2_RKE2Config is an autogenerated conversion function.
func Convert_v1alpha1_RKE2Config_To_v1alpha2_RKE2Config(in *RKE2Config, out *v1alpha2.RKE2Config, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2Config_To_v1alpha2_RKE2Config(in, out, s)
}

func autoConvert_v1alpha2_RKE2Config_To_v1alpha1_RKE2Config(in *v1alpha2.RKE2Config, out *RKE2Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_RKE2ConfigStatus_To_v1alpha1_RKE2ConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RKE2Config_To_v1alpha1_RKE2Config is an autogenerated conversion function.
func Convert_v1alpha2_RKE2Config_To_v1alpha1_RKE2Config(in *v1alpha2.RKE2Config, out *RKE2Config, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2Config_To_v1alpha1_RKE2Config(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigList_To_v1alpha2_RKE2ConfigList(in *RKE2ConfigList, out *v1alpha2.RKE2ConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.RKE2Config)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RKE2ConfigList_To_v1alpha2_RKE2ConfigList is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigList_To_v1alpha2_RKE2ConfigList(in *RKE2ConfigList, out *v1alpha2.RKE2ConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigList_To_v1alpha2_RKE2ConfigList(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigList_To_v1alpha1_RKE2ConfigList(in *v1alpha2.RKE2ConfigList, out *RKE2ConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RKE2Config)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_RKE2ConfigList_To_v1alpha1_RKE2ConfigList is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigList_To_v1alpha1_RKE2ConfigList(in *v1alpha2.RKE2ConfigList, out *RKE2ConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigList_To_v1alpha1_RKE2ConfigList(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec(in *RKE2ConfigSpec, out *v1alpha2.RKE2ConfigSpec, s conversion.Scope) error {
	out.Files = *(*[]v1alpha2.File)(unsafe.Pointer(&in.Files))
	out.PreRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PreRKE2Commands))
	out.PostRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PostRKE2Commands))
	if err := Convert_v1alpha1_RKE2AgentConfig_To_v1alpha2_RKE2AgentConfig(&in.AgentConfig, &out.AgentConfig, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Registry_To_v1alpha2_Registry(&in.PrivateRegistriesConfig, &out.PrivateRegistriesConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec(in *RKE2ConfigSpec, out *v1alpha2.RKE2ConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec(in *v1alpha2.RKE2ConfigSpec, out *RKE2ConfigSpec, s conversion.Scope) error {
	out.Files = *(*[]File)(unsafe.Pointer(&in.Files))
	out.PreRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PreRKE2Commands))
	out.PostRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PostRKE2Commands))
	if err := Convert_v1alpha2_RKE2AgentConfig_To_v1alpha1_RKE2AgentConfig(&in.AgentConfig, &out.AgentConfig, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_Registry_To_v1alpha1_Registry(&in.PrivateRegistriesConfig, &out.PrivateRegistriesConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec(in *v1alpha2.RKE2ConfigSpec, out *RKE2ConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigStatus_To_v1alpha2_RKE2ConfigStatus(in *RKE2ConfigStatus, out *v1alpha2.RKE2ConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_RKE2ConfigStatus_To_v1alpha2_RKE2ConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigStatus_To_v1alpha2_RKE2ConfigStatus(in *RKE2ConfigStatus, out *v1alpha2.RKE2ConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigStatus_To_v1alpha2_RKE2ConfigStatus(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigStatus_To_v1alpha1_RKE2ConfigStatus(in *v1alpha2.RKE2ConfigStatus, out *RKE2ConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_RKE2ConfigStatus_To_v1alpha1_RKE2ConfigStatus is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigStatus_To_v1alpha1_RKE2ConfigStatus(in *v1alpha2.RKE2ConfigStatus, out *RKE2ConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigStatus_To_v1alpha1_RKE2ConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigTemplate_To_v1alpha2_RKE2ConfigTemplate(in *RKE2ConfigTemplate, out *v1alpha2.RKE2ConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RKE2ConfigTemplateSpec_To_v1alpha2_RKE2ConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RKE2ConfigTemplate_To_v1alpha2_RKE2ConfigTemplate is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigTemplate_To_v1alpha2_RKE2ConfigTemplate(in *RKE2ConfigTemplate, out *v1alpha2.RKE2ConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigTemplate_To_v1alpha2_RKE2ConfigTemplate(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigTemplate_To_v1alpha1_RKE2ConfigTemplate(in *v1alpha2.RKE2ConfigTemplate, out *RKE2ConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_RKE2ConfigTemplateSpec_To_v1alpha1_RKE2ConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RKE2ConfigTemplate_To_v1alpha1_RKE2ConfigTemplate is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigTemplate_To_v1alpha1_RKE2ConfigTemplate(in *v1alpha2.RKE2ConfigTemplate, out *RKE2ConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigTemplate_To_v1alpha1_RKE2ConfigTemplate(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigTemplateList_To_v1alpha2_RKE2ConfigTemplateList(in *RKE2ConfigTemplateList, out *v1alpha2.RKE2ConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.RKE2ConfigTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RKE2ConfigTemplateList_To_v1alpha2_RKE2ConfigTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigTemplateList_To_v1alpha2_RKE2ConfigTemplateList(in *RKE2ConfigTemplateList, out *v1alpha2.RKE2ConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigTemplateList_To_v1alpha2_RKE2ConfigTemplateList(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigTemplateList_To_v1alpha1_RKE2ConfigTemplateList(in *v1alpha2.RKE2ConfigTemplateList, out *RKE2ConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RKE2ConfigTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_RKE2ConfigTemplateList_To_v1alpha1_RKE2ConfigTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigTemplateList_To_v1alpha1_RKE2ConfigTemplateList(in *v1alpha2.RKE2ConfigTemplateList, out *RKE2ConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigTemplateList_To_v1alpha1_RKE2ConfigTemplateList(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigTemplateResource_To_v1alpha2_RKE2ConfigTemplateResource(in *RKE2ConfigTemplateResource, out *v1alpha2.RKE2ConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha1_RKE2ConfigSpec_To_v1alpha2_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RKE2ConfigTemplateResource_To_v1alpha2_RKE2ConfigTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigTemplateResource_To_v1alpha2_RKE2ConfigTemplateResource(in *RKE2ConfigTemplateResource, out *v1alpha2.RKE2ConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigTemplateResource_To_v1alpha2_RKE2ConfigTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigTemplateResource_To_v1alpha1_RKE2ConfigTemplateResource(in *v1alpha2.RKE2ConfigTemplateResource, out *RKE2ConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha2_RKE2ConfigSpec_To_v1alpha1_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RKE2ConfigTemplateResource_To_v1alpha1_RKE2ConfigTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigTemplateResource_To_v1alpha1_RKE2ConfigTemplateResource(in *v1alpha2.RKE2ConfigTemplateResource, out *RKE2ConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigTemplateResource_To_v1alpha1_RKE2ConfigTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_RKE2ConfigTemplateSpec_To_v1alpha2_RKE2ConfigTemplateSpec(in *RKE2ConfigTemplateSpec, out *v1alpha2.RKE2ConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_RKE2ConfigTemplateResource_To_v1alpha2_RKE2ConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RKE2ConfigTemplateSpec_To_v1alpha2_RKE2ConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_RKE2ConfigTemplateSpec_To_v1alpha2_RKE2ConfigTemplateSpec(in *RKE2ConfigTemplateSpec, out *v1alpha2.RKE2ConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RKE2ConfigTemplateSpec_To_v1alpha2_RKE2ConfigTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_RKE2ConfigTemplateSpec_To_v1alpha1_RKE2ConfigTemplateSpec(in *v1alpha2.RKE2ConfigTemplateSpec, out *RKE2ConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_RKE2ConfigTemplateResource_To_v1alpha1_RKE2ConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RKE2ConfigTemplateSpec_To_v1alpha1_RKE2ConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_RKE2ConfigTemplateSpec_To_v1alpha1_RKE2ConfigTemplateSpec(in *v1alpha2.RKE2ConfigTemplateSpec, out *RKE2ConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_RKE2ConfigTemplateSpec_To_v1alpha1_RKE2ConfigTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_Registry_To_v1alpha2_Registry(in *Registry, out *v1alpha2.Registry, s conversion.Scope) error {
	out.Mirrors = *(*map[string]v1alpha2.Mirror)(unsafe.Pointer(&in.Mirrors))
	out.Configs = *(*map[string]v1alpha2.RegistryConfig)(unsafe.Pointer(&in.Configs))
	return nil
}

// Convert_v1alpha1_Registry_To_v1alpha2_Registry is an autogenerated conversion function.
func Convert_v1alpha1_Registry_To_v1alpha2_Registry(in *Registry, out *v1alpha2.Registry, s conversion.Scope) error {
	return autoConvert_v1alpha1_Registry_To_v1alpha2_Registry(in, out, s)
}

func autoConvert_v1alpha2_Registry_To_v1alpha1_Registry(in *v1alpha2.Registry, out *Registry, s conversion.Scope) error {
	out.Mirrors = *(*map[string]Mirror)(unsafe.Pointer(&in.Mirrors))
	out.Configs = *(*map[string]RegistryConfig)(unsafe.Pointer(&in.Configs))
	return nil
}

// Convert_v1alpha2_Registry_To_v1alpha1_Registry is an autogenerated conversion function.
func Convert_v1alpha2_Registry_To_v1alpha1_Registry(in *v1alpha2.Registry, out *Registry, s conversion.Scope) error {
	return autoConvert_v1alpha2_Registry_To_v1alpha1_Registry(in, out, s)
}

func autoConvert_v1alpha1_RegistryConfig_To_v1alpha2_RegistryConfig(in *RegistryConfig, out *v1alpha2.RegistryConfig, s conversion.Scope) error {
	out.AuthSecret = in.AuthSecret
	if err := Convert_v1alpha1_TLSConfig_To_v1alpha2_TLSConfig(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RegistryConfig_To_v1alpha2_RegistryConfig is an autogenerated conversion function.
func Convert_v1alpha1_RegistryConfig_To_v1alpha2_RegistryConfig(in *RegistryConfig, out *v1alpha2.RegistryConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegistryConfig_To_v1alpha2_RegistryConfig(in, out, s)
}

func autoConvert_v1alpha2_RegistryConfig_To_v1alpha1_RegistryConfig(in *v1alpha2.RegistryConfig, out *RegistryConfig, s conversion.Scope) error {
	out.AuthSecret = in.AuthSecret
	if err := Convert_v1alpha2_TLSConfig_To_v1alpha1_TLSConfig(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_RegistryConfig_To_v1alpha1_RegistryConfig is an autogenerated conversion function.
func Convert_v1alpha2_RegistryConfig_To_v1alpha1_RegistryConfig(in *v1alpha2.RegistryConfig, out *RegistryConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_RegistryConfig_To_v1alpha1_RegistryConfig(in, out, s)
}

func autoConvert_v1alpha1_SecretFileSource_To_v1alpha2_SecretFileSource(in *SecretFileSource, out *v1alpha2.SecretFileSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_SecretFileSource_To_v1alpha2_SecretFileSource is an autogenerated conversion function.
func Convert_v1alpha1_SecretFileSource_To_v1alpha2_SecretFileSource(in *SecretFileSource, out *v1alpha2.SecretFileSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretFileSource_To_v1alpha2_SecretFileSource(in, out, s)
}

func autoConvert_v1alpha2_SecretFileSource_To_v1alpha1_SecretFileSource(in *v1alpha2.SecretFileSource, out *SecretFileSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha2_SecretFileSource_To_v1alpha1_SecretFileSource is an autogenerated conversion function.
func Convert_v1alpha2_SecretFileSource_To_v1alpha1_SecretFileSource(in *v1alpha2.SecretFileSource, out *SecretFileSource, s conversion.Scope) error {
	return autoConvert_v1alpha2_SecretFileSource_To_v1alpha1_SecretFileSource(in, out, s)
}

func autoConvert_v1alpha1_TLSConfig_To_v1alpha2_TLSConfig(in *TLSConfig, out *v1alpha2.TLSConfig, s conversion.Scope) error {
	out.TLSConfigSecret = in.TLSConfigSecret
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1alpha1_TLSConfig_To_v1alpha2_TLSConfig is an autogenerated conversion function.
func Convert_v1alpha1_TLSConfig_To_v1alpha2_TLSConfig(in *TLSConfig, out *v1alpha2.TLSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLSConfig_To_v1alpha2_TLSConfig(in, out, s)
}

func autoConvert_v1alpha2_TLSConfig_To_v1alpha1_TLSConfig(in *v1alpha2.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	out.TLSConfigSecret = in.TLSConfigSecret
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1alpha2_TLSConfig_To_v1alpha1_TLSConfig is an autogenerated conversion function.
func Convert_v1alpha2_TLSConfig_To_v1alpha1_TLSConfig(in *v1alpha2.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_TLSConfig_To_v1alpha1_TLSConfig(in, out, s)
}
