/*
Copyright 2026 SUSE LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta2

import (
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// Conditions and condition Reasons for the RKE2ControlPlane object.

const (
	// MachinesReadyV1Beta1Condition reports an aggregate of current status of the machines controlled by the RKE2ControlPlane.
	MachinesReadyV1Beta1Condition clusterv1.ConditionType = "MachinesReady"
)

const (
	// AvailableV1Beta1Condition documents that the first control plane instance has completed the RKE2 initialization
	// and so the control plane is available and an API server instance is ready for processing requests.
	AvailableV1Beta1Condition clusterv1.ConditionType = "Available"

	// WaitingForRKE2ServerV1Beta1Reason (Severity=Info) documents a RKE2ControlPlane object waiting for the first
	// control plane instance to complete the RKE2 Server initialization.
	WaitingForRKE2ServerV1Beta1Reason = "WaitingForRKE2Server"
)

const (
	// ControlPlaneComponentsHealthyV1Beta1Condition reports the overall status of control plane components
	// implemented as static pods generated by RKE2 including kube-api-server, kube-controller manager,
	// kube-scheduler and etcd if managed.
	ControlPlaneComponentsHealthyV1Beta1Condition clusterv1.ConditionType = "ControlPlaneComponentsHealthy"

	// ControlPlaneComponentsUnhealthyV1Beta1Reason (Severity=Error) documents a control plane component not healthy.
	ControlPlaneComponentsUnhealthyV1Beta1Reason = "ControlPlaneComponentsUnhealthy"

	// ControlPlaneComponentsUnknownV1Beta1Reason reports a control plane component in unknown status.
	ControlPlaneComponentsUnknownV1Beta1Reason = "ControlPlaneComponentsUnknown"

	// ControlPlaneComponentsInspectionFailedV1Beta1Reason documents a failure in inspecting the control plane component status.
	ControlPlaneComponentsInspectionFailedV1Beta1Reason = "ControlPlaneComponentsInspectionFailed"

	// MachinesSpecUpToDateV1Beta1Condition documents that the spec of the machines controlled by the RKE2ControlPlane
	// is up to date. Whe this condition is false, the RKE2ControlPlane is executing a rolling upgrade.
	MachinesSpecUpToDateV1Beta1Condition clusterv1.ConditionType = "MachinesSpecUpToDate"

	// NodeMetadataUpToDateV1Beta1Condition documents that the metadata of the nodes controlled by the RKE2 machines
	// is up to date. When this condition is false, or missing the node metadata is not propagated.
	NodeMetadataUpToDateV1Beta1Condition clusterv1.ConditionType = "NodeMetadataUpToDate"

	// MachineAgentHealthyV1Beta1Condition reports a machine's rke2 agent's operational status.
	MachineAgentHealthyV1Beta1Condition clusterv1.ConditionType = "AgentHealthy"

	// NodePatchFailedV1Beta1Reason (Severity=Error) documents reason why Node object could not be patched.
	NodePatchFailedV1Beta1Reason = "NodePatchFailed"

	// PodInspectionFailedV1Beta1Reason documents a failure in inspecting the pod status.
	PodInspectionFailedV1Beta1Reason = "PodInspectionFailed"

	// PodMissingV1Beta1Reason (Severity=Error) documents a pod does not exist.
	PodMissingV1Beta1Reason = "PodMissing" // RollingUpdateInProgressV1Beta1Reason (Severity=Warning) documents a RKE2ControlPlane object executing a

	// PodFailedV1Beta1Reason (Severity=Error) documents if a pod failed during provisioning i.e., e.g CrashLoopbackOff, ImagePullBackOff
	// or if all the containers in a pod have terminated.
	PodFailedV1Beta1Reason = "PodFailed"

	// RollingUpdateInProgressV1Beta1Reason (Severity=Warning) documents a RKE2ControlPlane object executing a
	// rolling upgrade for aligning the machines spec to the desired state.
	RollingUpdateInProgressV1Beta1Reason = "RollingUpdateInProgress"
)

const (
	// EtcdClusterHealthyV1Beta1Condition documents the overall etcd cluster's health.
	EtcdClusterHealthyV1Beta1Condition clusterv1.ConditionType = "EtcdClusterHealthy"

	// EtcdClusterInspectionFailedV1Beta1Reason documents a failure in inspecting the etcd cluster status.
	EtcdClusterInspectionFailedV1Beta1Reason = "EtcdClusterInspectionFailed"

	// EtcdClusterUnknownV1Beta1Reason reports an etcd cluster in unknown status.
	EtcdClusterUnknownV1Beta1Reason = "EtcdClusterUnknown"

	// EtcdClusterUnhealthyV1Beta1Reason (Severity=Error) is set when the etcd cluster is unhealthy.
	EtcdClusterUnhealthyV1Beta1Reason = "EtcdClusterUnhealthy"

	// MachineEtcdMemberHealthyV1Beta1Condition report the machine's etcd member's health status.
	// NOTE: This conditions exists only if a stacked etcd cluster is used.
	MachineEtcdMemberHealthyV1Beta1Condition clusterv1.ConditionType = "EtcdMemberHealthy"

	// EtcdMemberInspectionFailedV1Beta1Reason documents a failure in inspecting the etcd member status.
	EtcdMemberInspectionFailedV1Beta1Reason = "MemberInspectionFailed"

	// ResizedV1Beta1Condition documents a RKE2ControlPlane that is resizing the set of controlled machines.
	ResizedV1Beta1Condition clusterv1.ConditionType = "Resized"

	// ScalingUpV1Beta1Reason (Severity=Info) documents a RKE2ControlPlane that is increasing the number of replicas.
	ScalingUpV1Beta1Reason = "ScalingUp"

	// ScalingDownV1Beta1Reason (Severity=Info) documents a RKE2ControlPlane that is decreasing the number of replicas.
	ScalingDownV1Beta1Reason = "ScalingDown"
)

const (
	// CertificatesAvailableV1Beta1Condition documents the overall status of the certificates generated by the RKE2ControlPlane.
	CertificatesAvailableV1Beta1Condition clusterv1.ConditionType = "CertificatesAvailable"

	// CertificatesGenerationFailedV1Beta1Reason documents a failure in generating the certificates.
	CertificatesGenerationFailedV1Beta1Reason = "CertificateGenerationFailed"
)
