/*
Copyright 2026 SUSE.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

import (
	clusterv1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
)

// RKE2ControlPlane's Available condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneAvailableV1Beta2Condition is true if RKE2ControlPlane is not deleted, `CertificatesAvailable` is true,
	// at least one Machine with healthy control plane components, and etcd has enough operational members to meet quorum requirements.
	// More specifically, considering how kubeadm layouts components:
	// -  Kubernetes API server, scheduler and controller manager health is inferred by the status of
	//    the corresponding Pods hosted on each machine.
	// -  In case of managed etcd, also a healthy etcd Pod and a healthy etcd member must exist on the same
	//    machine with the healthy Kubernetes API server, scheduler and controller manager, otherwise the k8s control
	//    plane cannot be considered operational (if etcd is not operational on a machine, most likely also API server,
	//    scheduler and controller manager on the same machine will be impacted).
	// -  In case of external etcd, KCP cannot make any assumption on etcd status, so all the etcd checks are skipped.
	//
	// Please note that when this condition is true, partial unavailability will be surfaced in the condition message,
	// but with a 10s delay to ensure flakes do not impact condition stability.
	RKE2ControlPlaneAvailableV1Beta2Condition = clusterv1beta1.AvailableV1Beta2Condition

	// RKE2ControlPlaneAvailableInspectionFailedV1Beta2Reason documents a failure when inspecting the status of the
	// etcd cluster hosted on RKE2ControlPlane controlled machines.
	RKE2ControlPlaneAvailableInspectionFailedV1Beta2Reason = clusterv1beta1.InspectionFailedV1Beta2Reason

	// RKE2ControlPlaneAvailableV1Beta2Reason surfaces when the RKE2ControlPlane is available.
	RKE2ControlPlaneAvailableV1Beta2Reason = clusterv1beta1.AvailableV1Beta2Reason

	// RKE2ControlPlaneNotAvailableV1Beta2Reason surfaces when the RKE2ControlPlane is not available.
	RKE2ControlPlaneNotAvailableV1Beta2Reason = clusterv1beta1.NotAvailableV1Beta2Reason
)

// RKE2ControlPlane's Initialized condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneInitializedV1Beta2Condition is true when the control plane is functional enough to accept
	// requests. This information is usually used as a signal for starting all the provisioning operations that
	// depend on a functional API server, but do not require a full HA control plane to exist.
	RKE2ControlPlaneInitializedV1Beta2Condition = "Initialized"

	// RKE2ControlPlaneInitializedV1Beta2Reason surfaces when the control plane is initialized.
	RKE2ControlPlaneInitializedV1Beta2Reason = "Initialized"

	// RKE2ControlPlaneNotInitializedV1Beta2Reason surfaces when the control plane is not initialized.
	RKE2ControlPlaneNotInitializedV1Beta2Reason = "NotInitialized"
)

// RKE2ControlPlane's CertificatesAvailable condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneCertificatesAvailableV1Beta2Condition True if all the cluster certificates exist.
	RKE2ControlPlaneCertificatesAvailableV1Beta2Condition = "CertificatesAvailable"

	// RKE2ControlPlaneCertificatesInternalErrorV1Beta2Reason surfaces unexpected failures when reconciling cluster certificates.
	RKE2ControlPlaneCertificatesInternalErrorV1Beta2Reason = clusterv1beta1.InternalErrorV1Beta2Reason

	// RKE2ControlPlaneCertificatesAvailableV1Beta2Reason surfaces when cluster certificates are available,
	// no matter if those certificates have been provided by the user or generated by  RKE2ControlPlane itself.
	// Cluster certificates include: certificate authorities for ca, sa, front-proxy, etcd, and if external etcd is used,
	// also the apiserver-etcd-client client certificate.
	RKE2ControlPlaneCertificatesAvailableV1Beta2Reason = clusterv1beta1.AvailableV1Beta2Reason
)

// RKE2ControlPlane's EtcdClusterHealthy condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneEtcdClusterHealthyV1Beta2Condition surfaces issues to etcd cluster hosted on machines managed by this object.
	// It is computed as aggregation of Machine's EtcdMemberHealthy conditions plus additional checks validating
	// potential issues to etcd quorum.
	// Note: this condition is not set when using an external etcd.
	RKE2ControlPlaneEtcdClusterHealthyV1Beta2Condition = "EtcdClusterHealthy"

	// RKE2ControlPlaneEtcdClusterInspectionFailedV1Beta2Reason documents a failure when inspecting the status of the
	// etcd cluster hosted on RKE2ControlPlane controlled machines.
	RKE2ControlPlaneEtcdClusterInspectionFailedV1Beta2Reason = clusterv1beta1.InspectionFailedV1Beta2Reason

	// RKE2ControlPlaneEtcdClusterConnectionDownV1Beta2Reason surfaces that the connection to the workload
	// cluster is down.
	RKE2ControlPlaneEtcdClusterConnectionDownV1Beta2Reason = clusterv1beta1.ConnectionDownV1Beta2Reason

	// RKE2ControlPlaneEtcdClusterHealthyV1Beta2Reason surfaces when the etcd cluster hosted on RKE2ControlPlane
	// machines is healthy.
	RKE2ControlPlaneEtcdClusterHealthyV1Beta2Reason = "Healthy"

	// RKE2ControlPlaneEtcdClusterNotHealthyV1Beta2Reason surfaces when the etcd cluster hosted on RKE2ControlPlane
	// machines is not healthy.
	RKE2ControlPlaneEtcdClusterNotHealthyV1Beta2Reason = "NotHealthy"

	// RKE2ControlPlaneEtcdClusterHealthUnknownV1Beta2Reason surfaces when the health status of the etcd cluster hosted
	// on RKE2ControlPlane machines is unknown.
	RKE2ControlPlaneEtcdClusterHealthUnknownV1Beta2Reason = "HealthUnknown"
)

// RKE2ControlPlane's ControlPlaneComponentsHealthy condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneControlPlaneComponentsHealthyV1Beta2Condition surfaces issues to Kubernetes control plane components
	// hosted on machines managed by this object. It is computed as aggregation of Machine's `APIServerPodHealthy`,
	// `ControllerManagerPodHealthy`, `SchedulerPodHealthy`, `EtcdPodHealthy` conditions plus additional checks on
	// control plane machines and nodes.
	RKE2ControlPlaneControlPlaneComponentsHealthyV1Beta2Condition = "ControlPlaneComponentsHealthy"

	// RKE2ControlPlaneControlPlaneComponentsInspectionFailedV1Beta2Reason documents a failure when inspecting the status of the
	// control plane components hosted on RKE2ControlPlane controlled machines.
	RKE2ControlPlaneControlPlaneComponentsInspectionFailedV1Beta2Reason = clusterv1beta1.InspectionFailedV1Beta2Reason

	// RKE2ControlPlaneControlPlaneComponentsConnectionDownV1Beta2Reason surfaces that the connection to the workload
	// cluster is down.
	RKE2ControlPlaneControlPlaneComponentsConnectionDownV1Beta2Reason = clusterv1beta1.ConnectionDownV1Beta2Reason

	// RKE2ControlPlaneControlPlaneComponentsHealthyV1Beta2Reason surfaces when the Kubernetes control plane components
	// hosted on RKE2ControlPlane machines are healthy.
	RKE2ControlPlaneControlPlaneComponentsHealthyV1Beta2Reason = "Healthy"

	// RKE2ControlPlaneControlPlaneComponentsNotHealthyV1Beta2Reason surfaces when the Kubernetes control plane components
	// hosted on RKE2ControlPlane machines are not healthy.
	RKE2ControlPlaneControlPlaneComponentsNotHealthyV1Beta2Reason = "NotHealthy"

	// RKE2ControlPlaneControlPlaneComponentsHealthUnknownV1Beta2Reason surfaces when the health status of the
	// Kubernetes control plane components hosted on RKE2ControlPlane machines is unknown.
	RKE2ControlPlaneControlPlaneComponentsHealthUnknownV1Beta2Reason = "HealthUnknown"
)

// RKE2ControlPlane's MachinesReady condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneMachinesReadyV1Beta2Condition surfaces detail of issues on the controlled machines, if any.
	// Please note this will include also APIServerPodHealthy, ControllerManagerPodHealthy, SchedulerPodHealthy conditions.
	// If not using an external etcd also EtcdPodHealthy, EtcdMemberHealthy conditions are included.
	RKE2ControlPlaneMachinesReadyV1Beta2Condition = clusterv1beta1.MachinesReadyV1Beta2Condition

	// RKE2ControlPlaneMachinesReadyV1Beta2Reason surfaces when all the controlled machine's Ready conditions are true.
	RKE2ControlPlaneMachinesReadyV1Beta2Reason = clusterv1beta1.ReadyV1Beta2Reason

	// RKE2ControlPlaneMachinesNotReadyV1Beta2Reason surfaces when at least one of the controlled machine's Ready conditions is false.
	RKE2ControlPlaneMachinesNotReadyV1Beta2Reason = clusterv1beta1.NotReadyV1Beta2Reason

	// RKE2ControlPlaneMachinesReadyUnknownV1Beta2Reason surfaces when at least one of the controlled machine's Ready conditions is unknown
	// and no one of the controlled machine's Ready conditions is false.
	RKE2ControlPlaneMachinesReadyUnknownV1Beta2Reason = clusterv1beta1.ReadyUnknownV1Beta2Reason

	// RKE2ControlPlaneMachinesReadyNoReplicasV1Beta2Reason surfaces when no machines exist for the RKE2ControlPlane.
	RKE2ControlPlaneMachinesReadyNoReplicasV1Beta2Reason = clusterv1beta1.NoReplicasV1Beta2Reason

	// RKE2ControlPlaneMachinesReadyInternalErrorV1Beta2Reason surfaces unexpected failures when computing the MachinesReady condition.
	RKE2ControlPlaneMachinesReadyInternalErrorV1Beta2Reason = clusterv1beta1.InternalErrorV1Beta2Reason
)

// RKE2ControlPlane's MachinesUpToDate condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneMachinesUpToDateV1Beta2Condition surfaces details of controlled machines not up to date, if any.
	// Note: New machines are considered 10s after machine creation. This gives time to the machine's owner controller to recognize the new machine and add the UpToDate condition.
	RKE2ControlPlaneMachinesUpToDateV1Beta2Condition = clusterv1beta1.MachinesUpToDateV1Beta2Condition

	// RKE2ControlPlaneMachinesUpToDateV1Beta2Reason surfaces when all the controlled machine's UpToDate conditions are true.
	RKE2ControlPlaneMachinesUpToDateV1Beta2Reason = clusterv1beta1.UpToDateV1Beta2Reason

	// RKE2ControlPlaneMachinesNotUpToDateV1Beta2Reason surfaces when at least one of the controlled machine's UpToDate conditions is false.
	RKE2ControlPlaneMachinesNotUpToDateV1Beta2Reason = clusterv1beta1.NotUpToDateV1Beta2Reason

	// RKE2ControlPlaneMachinesUpToDateUnknownV1Beta2Reason surfaces when at least one of the controlled machine's UpToDate conditions is unknown
	// and no one of the controlled machine's UpToDate conditions is false.
	RKE2ControlPlaneMachinesUpToDateUnknownV1Beta2Reason = clusterv1beta1.UpToDateUnknownV1Beta2Reason

	// RKE2ControlPlaneMachinesUpToDateNoReplicasV1Beta2Reason surfaces when no machines exist for the RKE2ControlPlane.
	RKE2ControlPlaneMachinesUpToDateNoReplicasV1Beta2Reason = clusterv1beta1.NoReplicasV1Beta2Reason

	// RKE2ControlPlaneMachinesUpToDateInternalErrorV1Beta2Reason surfaces unexpected failures when computing the MachinesUpToDate condition.
	RKE2ControlPlaneMachinesUpToDateInternalErrorV1Beta2Reason = clusterv1beta1.InternalErrorV1Beta2Reason
)

// RKE2ControlPlane's RollingOut condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneRollingOutV1Beta2Condition  is true if there is at least one machine not up-to-date.
	RKE2ControlPlaneRollingOutV1Beta2Condition = clusterv1beta1.RollingOutV1Beta2Condition

	// RKE2ControlPlaneRollingOutV1Beta2Reason  surfaces when there is at least one machine not up-to-date.
	RKE2ControlPlaneRollingOutV1Beta2Reason = clusterv1beta1.RollingOutV1Beta2Reason

	// RKE2ControlPlaneNotRollingOutV1Beta2Reason surfaces when all the machines are up-to-date.
	RKE2ControlPlaneNotRollingOutV1Beta2Reason = clusterv1beta1.NotRollingOutV1Beta2Reason
)

// RKE2ControlPlane's ScalingUp condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneScalingUpV1Beta2Condition is true if actual replicas < desired replicas.
	// Note: In case a RKE2ControlPlane preflight check is preventing scale up, this will surface in the condition message.
	RKE2ControlPlaneScalingUpV1Beta2Condition = clusterv1beta1.ScalingUpV1Beta2Condition

	// RKE2ControlPlaneScalingUpV1Beta2Reason surfaces when actual replicas < desired replicas.
	RKE2ControlPlaneScalingUpV1Beta2Reason = clusterv1beta1.ScalingUpV1Beta2Reason

	// RKE2ControlPlaneNotScalingUpV1Beta2Reason surfaces when actual replicas >= desired replicas.
	RKE2ControlPlaneNotScalingUpV1Beta2Reason = clusterv1beta1.NotScalingUpV1Beta2Reason

	// RKE2ControlPlaneScalingUpWaitingForReplicasSetV1Beta2Reason surfaces when the .spec.replicas
	// field of the RKE2ControlPlane is not set.
	RKE2ControlPlaneScalingUpWaitingForReplicasSetV1Beta2Reason = clusterv1beta1.WaitingForReplicasSetV1Beta2Reason
)

// RKE2ControlPlane's ScalingDown condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneScalingDownV1Beta2Condition is true if actual replicas > desired replicas.
	// Note: In case a RKE2ControlPlane preflight check is preventing scale down, this will surface in the condition message.
	RKE2ControlPlaneScalingDownV1Beta2Condition = clusterv1beta1.ScalingDownV1Beta2Condition

	// RKE2ControlPlaneScalingDownV1Beta2Reason surfaces when actual replicas > desired replicas.
	RKE2ControlPlaneScalingDownV1Beta2Reason = clusterv1beta1.ScalingDownV1Beta2Reason

	// RKE2ControlPlaneNotScalingDownV1Beta2Reason surfaces when actual replicas <= desired replicas.
	RKE2ControlPlaneNotScalingDownV1Beta2Reason = clusterv1beta1.NotScalingDownV1Beta2Reason

	// RKE2ControlPlaneScalingDownWaitingForReplicasSetV1Beta2Reason surfaces when the .spec.replicas
	// field of the RKE2ControlPlane is not set.
	RKE2ControlPlaneScalingDownWaitingForReplicasSetV1Beta2Reason = clusterv1beta1.WaitingForReplicasSetV1Beta2Reason
)

// RKE2ControlPlane's Remediating condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneRemediatingV1Beta2Condition surfaces details about ongoing remediation of the controlled machines, if any.
	// Note: RKE2ControlPlane only remediates machines with HealthCheckSucceeded set to false and with the OwnerRemediated condition set to false.
	RKE2ControlPlaneRemediatingV1Beta2Condition = clusterv1beta1.RemediatingV1Beta2Condition

	// RKE2ControlPlaneRemediatingV1Beta2Reason surfaces when the RKE2ControlPlane has at least one machine with HealthCheckSucceeded set to false
	// and with the OwnerRemediated condition set to false.
	RKE2ControlPlaneRemediatingV1Beta2Reason = clusterv1beta1.RemediatingV1Beta2Reason

	// RKE2ControlPlaneNotRemediatingV1Beta2Reason surfaces when the RKE2ControlPlane does not have any machine with HealthCheckSucceeded set to false
	// and with the OwnerRemediated condition set to false.
	RKE2ControlPlaneNotRemediatingV1Beta2Reason = clusterv1beta1.NotRemediatingV1Beta2Reason

	// RKE2ControlPlaneRemediatingInternalErrorV1Beta2Reason surfaces unexpected failures when computing the Remediating condition.
	RKE2ControlPlaneRemediatingInternalErrorV1Beta2Reason = clusterv1beta1.InternalErrorV1Beta2Reason
)

// Reasons that will be used for the OwnerRemediated condition set by MachineHealthCheck on RKE2ControlPlane controlled machines
// being remediated in v1Beta2 API version.
const (
	// RKE2ControlPlaneMachineRemediationInternalErrorV1Beta2Reason surfaces unexpected failures while remediating a control plane machine.
	RKE2ControlPlaneMachineRemediationInternalErrorV1Beta2Reason = clusterv1beta1.InternalErrorV1Beta2Reason

	// RKE2ControlPlaneMachineCannotBeRemediatedV1Beta2Reason surfaces when remediation of a control plane machine can't be started.
	RKE2ControlPlaneMachineCannotBeRemediatedV1Beta2Reason = "CannotBeRemediated"

	// RKE2ControlPlaneMachineRemediationDeferredV1Beta2Reason surfaces when remediation of a control plane machine must be deferred.
	RKE2ControlPlaneMachineRemediationDeferredV1Beta2Reason = "RemediationDeferred"

	// RKE2ControlPlaneMachineRemediationMachineDeletingV1Beta2Reason surfaces when remediation of a control plane machine
	// has been completed by deleting the unhealthy machine.
	// Note: After an unhealthy machine is deleted, a new one is created by the RKE2ControlPlaneMachine as part of the
	// regular reconcile loop that ensures the correct number of replicas exist; RKE2ControlPlane machine waits for
	// the new machine to exists before removing the controlplane.cluster.x-k8s.io/remediation-in-progress annotation.
	// This is part of a series of safeguards to ensure that operation are performed sequentially on control plane machines.
	RKE2ControlPlaneMachineRemediationMachineDeletingV1Beta2Reason = "MachineDeleting"
)

// RKE2ControlPlane's Deleting condition and corresponding reasons that will be used in v1Beta2 API version.
const (
	// RKE2ControlPlaneDeletingV1Beta2Condition surfaces details about ongoing deletion of the controlled machines.
	RKE2ControlPlaneDeletingV1Beta2Condition = clusterv1beta1.DeletingV1Beta2Condition

	// RKE2ControlPlaneNotDeletingV1Beta2Reason surfaces when the KCP is not deleting because the
	// DeletionTimestamp is not set.
	RKE2ControlPlaneNotDeletingV1Beta2Reason = clusterv1beta1.NotDeletingV1Beta2Reason

	// RKE2ControlPlaneDeletingWaitingForWorkersDeletionV1Beta2Reason surfaces when the KCP deletion
	// waits for the workers to be deleted.
	RKE2ControlPlaneDeletingWaitingForWorkersDeletionV1Beta2Reason = "WaitingForWorkersDeletion"

	// RKE2ControlPlaneDeletingWaitingForMachineDeletionV1Beta2Reason surfaces when the KCP deletion
	// waits for the control plane Machines to be deleted.
	RKE2ControlPlaneDeletingWaitingForMachineDeletionV1Beta2Reason = "WaitingForMachineDeletion"

	// RKE2ControlPlaneDeletingDeletionCompletedV1Beta2Reason surfaces when the KCP deletion has been completed.
	// This reason is set right after the `kubeadm.controlplane.cluster.x-k8s.io` finalizer is removed.
	// This means that the object will go away (i.e. be removed from etcd), except if there are other
	// finalizers on the KCP object.
	RKE2ControlPlaneDeletingDeletionCompletedV1Beta2Reason = clusterv1beta1.DeletionCompletedV1Beta2Reason

	// RKE2ControlPlaneDeletingInternalErrorV1Beta2Reason surfaces unexpected failures when deleting a KCP object.
	RKE2ControlPlaneDeletingInternalErrorV1Beta2Reason = clusterv1beta1.InternalErrorV1Beta2Reason
)

// APIServerPodHealthy, ControllerManagerPodHealthy, SchedulerPodHealthy and EtcdPodHealthy condition and corresponding
// reasons that will be used for RKE2ControlPlane controlled machines in v1Beta2 API version.
const (
	// RKE2ControlPlaneMachineAPIServerPodHealthyV1Beta2Condition surfaces the status of the API server pod hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachineAPIServerPodHealthyV1Beta2Condition = "APIServerPodHealthy"

	// RKE2ControlPlaneMachineControllerManagerPodHealthyV1Beta2Condition surfaces the status of the controller manager pod hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachineControllerManagerPodHealthyV1Beta2Condition = "ControllerManagerPodHealthy"

	// RKE2ControlPlaneMachineSchedulerPodHealthyV1Beta2Condition surfaces the status of the scheduler pod hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachineSchedulerPodHealthyV1Beta2Condition = "SchedulerPodHealthy"

	// RKE2ControlPlaneMachineEtcdPodHealthyV1Beta2Condition surfaces the status of the etcd pod hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachineEtcdPodHealthyV1Beta2Condition = "EtcdPodHealthy"

	// RKE2ControlPlaneMachinePodRunningV1Beta2Reason surfaces a pod hosted on a RKE2ControlPlane controlled machine that is running.
	RKE2ControlPlaneMachinePodRunningV1Beta2Reason = "Running"

	// RKE2ControlPlaneMachinePodProvisioningV1Beta2Reason surfaces a pod hosted on a RKE2ControlPlane controlled machine
	// waiting to be provisioned i.e., Pod is in "Pending" phase.
	RKE2ControlPlaneMachinePodProvisioningV1Beta2Reason = "Provisioning"

	// RKE2ControlPlaneMachinePodDoesNotExistV1Beta2Reason surfaces a when a pod hosted on a RKE2ControlPlane controlled machine
	// does not exist.
	RKE2ControlPlaneMachinePodDoesNotExistV1Beta2Reason = "DoesNotExist"

	// RKE2ControlPlaneMachinePodFailedV1Beta2Reason surfaces a when a pod hosted on a RKE2ControlPlane controlled machine
	// failed during provisioning, e.g. CrashLoopBackOff, ImagePullBackOff or if all the containers in a pod have terminated.
	RKE2ControlPlaneMachinePodFailedV1Beta2Reason = "Failed"

	// RKE2ControlPlaneMachinePodInspectionFailedV1Beta2Reason documents a failure when inspecting the status of a
	// pod hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachinePodInspectionFailedV1Beta2Reason = clusterv1beta1.InspectionFailedV1Beta2Reason

	// RKE2ControlPlaneMachinePodConnectionDownV1Beta2Reason surfaces that the connection to the workload
	// cluster is down.
	RKE2ControlPlaneMachinePodConnectionDownV1Beta2Reason = clusterv1beta1.ConnectionDownV1Beta2Reason

	// RKE2ControlPlaneMachinePodDeletingV1Beta2Reason surfaces when the machine hosting control plane components
	// is being deleted.
	RKE2ControlPlaneMachinePodDeletingV1Beta2Reason = "Deleting"
)

// EtcdMemberHealthy condition and corresponding reasons that will be used for RKE2ControlPlane controlled machines in v1Beta2 API version.
const (
	// RKE2ControlPlaneMachineEtcdMemberHealthyV1Beta2Condition surfaces the status of the etcd member hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachineEtcdMemberHealthyV1Beta2Condition = "EtcdMemberHealthy"

	// RKE2ControlPlaneMachineEtcdMemberNotHealthyV1Beta2Reason surfaces when the etcd member hosted on a RKE2ControlPlane controlled machine is not healthy.
	RKE2ControlPlaneMachineEtcdMemberNotHealthyV1Beta2Reason = "NotHealthy"

	// RKE2ControlPlaneMachineEtcdMemberHealthyV1Beta2Reason surfaces when the etcd member hosted on a RKE2ControlPlane controlled machine is healthy.
	RKE2ControlPlaneMachineEtcdMemberHealthyV1Beta2Reason = "Healthy"

	// RKE2ControlPlaneMachineEtcdMemberInspectionFailedV1Beta2Reason documents a failure when inspecting the status of an
	// etcd member hosted on a RKE2ControlPlane controlled machine.
	RKE2ControlPlaneMachineEtcdMemberInspectionFailedV1Beta2Reason = clusterv1beta1.InspectionFailedV1Beta2Reason

	// RKE2ControlPlaneMachineEtcdMemberConnectionDownV1Beta2Reason surfaces that the connection to the workload
	// cluster is down.
	RKE2ControlPlaneMachineEtcdMemberConnectionDownV1Beta2Reason = clusterv1beta1.ConnectionDownV1Beta2Reason

	// RKE2ControlPlaneMachineEtcdMemberDeletingV1Beta2Reason surfaces when the machine hosting an etcd member
	// is being deleted.
	RKE2ControlPlaneMachineEtcdMemberDeletingV1Beta2Reason = "Deleting"
)
