//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 SUSE LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	apiv1beta1 "github.com/rancher/cluster-api-provider-rke2/bootstrap/api/v1beta1"
	apiv1beta2 "github.com/rancher/cluster-api-provider-rke2/bootstrap/api/v1beta2"
	v1beta2 "github.com/rancher/cluster-api-provider-rke2/controlplane/api/v1beta2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DisableComponents)(nil), (*v1beta2.DisableComponents)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DisableComponents_To_v1beta2_DisableComponents(a.(*DisableComponents), b.(*v1beta2.DisableComponents), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.DisableComponents)(nil), (*DisableComponents)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_DisableComponents_To_v1beta1_DisableComponents(a.(*v1beta2.DisableComponents), b.(*DisableComponents), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdBackupConfig)(nil), (*v1beta2.EtcdBackupConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdBackupConfig_To_v1beta2_EtcdBackupConfig(a.(*EtcdBackupConfig), b.(*v1beta2.EtcdBackupConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EtcdBackupConfig)(nil), (*EtcdBackupConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EtcdBackupConfig_To_v1beta1_EtcdBackupConfig(a.(*v1beta2.EtcdBackupConfig), b.(*EtcdBackupConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdConfig)(nil), (*v1beta2.EtcdConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdConfig_To_v1beta2_EtcdConfig(a.(*EtcdConfig), b.(*v1beta2.EtcdConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EtcdConfig)(nil), (*EtcdConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EtcdConfig_To_v1beta1_EtcdConfig(a.(*v1beta2.EtcdConfig), b.(*EtcdConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdS3)(nil), (*v1beta2.EtcdS3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdS3_To_v1beta2_EtcdS3(a.(*EtcdS3), b.(*v1beta2.EtcdS3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EtcdS3)(nil), (*EtcdS3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EtcdS3_To_v1beta1_EtcdS3(a.(*v1beta2.EtcdS3), b.(*EtcdS3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LastRemediationStatus)(nil), (*v1beta2.LastRemediationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(a.(*LastRemediationStatus), b.(*v1beta2.LastRemediationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.LastRemediationStatus)(nil), (*LastRemediationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(a.(*v1beta2.LastRemediationStatus), b.(*LastRemediationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlane)(nil), (*v1beta2.RKE2ControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlane_To_v1beta2_RKE2ControlPlane(a.(*RKE2ControlPlane), b.(*v1beta2.RKE2ControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlane)(nil), (*RKE2ControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlane_To_v1beta1_RKE2ControlPlane(a.(*v1beta2.RKE2ControlPlane), b.(*RKE2ControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneCustomDefaulter)(nil), (*v1beta2.RKE2ControlPlaneCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneCustomDefaulter_To_v1beta2_RKE2ControlPlaneCustomDefaulter(a.(*RKE2ControlPlaneCustomDefaulter), b.(*v1beta2.RKE2ControlPlaneCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneCustomDefaulter)(nil), (*RKE2ControlPlaneCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneCustomDefaulter_To_v1beta1_RKE2ControlPlaneCustomDefaulter(a.(*v1beta2.RKE2ControlPlaneCustomDefaulter), b.(*RKE2ControlPlaneCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneCustomValidator)(nil), (*v1beta2.RKE2ControlPlaneCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneCustomValidator_To_v1beta2_RKE2ControlPlaneCustomValidator(a.(*RKE2ControlPlaneCustomValidator), b.(*v1beta2.RKE2ControlPlaneCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneCustomValidator)(nil), (*RKE2ControlPlaneCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneCustomValidator_To_v1beta1_RKE2ControlPlaneCustomValidator(a.(*v1beta2.RKE2ControlPlaneCustomValidator), b.(*RKE2ControlPlaneCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneList)(nil), (*v1beta2.RKE2ControlPlaneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneList_To_v1beta2_RKE2ControlPlaneList(a.(*RKE2ControlPlaneList), b.(*v1beta2.RKE2ControlPlaneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneList)(nil), (*RKE2ControlPlaneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneList_To_v1beta1_RKE2ControlPlaneList(a.(*v1beta2.RKE2ControlPlaneList), b.(*RKE2ControlPlaneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneTemplate)(nil), (*RKE2ControlPlaneTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneTemplate_To_v1beta1_RKE2ControlPlaneTemplate(a.(*v1beta2.RKE2ControlPlaneTemplate), b.(*RKE2ControlPlaneTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneTemplateCustomDefaulter)(nil), (*v1beta2.RKE2ControlPlaneTemplateCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter(a.(*RKE2ControlPlaneTemplateCustomDefaulter), b.(*v1beta2.RKE2ControlPlaneTemplateCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneTemplateCustomDefaulter)(nil), (*RKE2ControlPlaneTemplateCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter(a.(*v1beta2.RKE2ControlPlaneTemplateCustomDefaulter), b.(*RKE2ControlPlaneTemplateCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneTemplateCustomValidator)(nil), (*v1beta2.RKE2ControlPlaneTemplateCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneTemplateCustomValidator_To_v1beta2_RKE2ControlPlaneTemplateCustomValidator(a.(*RKE2ControlPlaneTemplateCustomValidator), b.(*v1beta2.RKE2ControlPlaneTemplateCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneTemplateCustomValidator)(nil), (*RKE2ControlPlaneTemplateCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneTemplateCustomValidator_To_v1beta1_RKE2ControlPlaneTemplateCustomValidator(a.(*v1beta2.RKE2ControlPlaneTemplateCustomValidator), b.(*RKE2ControlPlaneTemplateCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneTemplateList)(nil), (*v1beta2.RKE2ControlPlaneTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneTemplateList_To_v1beta2_RKE2ControlPlaneTemplateList(a.(*RKE2ControlPlaneTemplateList), b.(*v1beta2.RKE2ControlPlaneTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneTemplateList)(nil), (*RKE2ControlPlaneTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneTemplateList_To_v1beta1_RKE2ControlPlaneTemplateList(a.(*v1beta2.RKE2ControlPlaneTemplateList), b.(*RKE2ControlPlaneTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneTemplateResource)(nil), (*v1beta2.RKE2ControlPlaneTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneTemplateResource_To_v1beta2_RKE2ControlPlaneTemplateResource(a.(*RKE2ControlPlaneTemplateResource), b.(*v1beta2.RKE2ControlPlaneTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneTemplateResource)(nil), (*RKE2ControlPlaneTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneTemplateResource_To_v1beta1_RKE2ControlPlaneTemplateResource(a.(*v1beta2.RKE2ControlPlaneTemplateResource), b.(*RKE2ControlPlaneTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ControlPlaneTemplateSpec)(nil), (*v1beta2.RKE2ControlPlaneTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneTemplateSpec_To_v1beta2_RKE2ControlPlaneTemplateSpec(a.(*RKE2ControlPlaneTemplateSpec), b.(*v1beta2.RKE2ControlPlaneTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ControlPlaneTemplateSpec)(nil), (*RKE2ControlPlaneTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneTemplateSpec_To_v1beta1_RKE2ControlPlaneTemplateSpec(a.(*v1beta2.RKE2ControlPlaneTemplateSpec), b.(*RKE2ControlPlaneTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ServerConfig)(nil), (*v1beta2.RKE2ServerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ServerConfig_To_v1beta2_RKE2ServerConfig(a.(*RKE2ServerConfig), b.(*v1beta2.RKE2ServerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ServerConfig)(nil), (*RKE2ServerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ServerConfig_To_v1beta1_RKE2ServerConfig(a.(*v1beta2.RKE2ServerConfig), b.(*RKE2ServerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RemediationStrategy)(nil), (*v1beta2.RemediationStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(a.(*RemediationStrategy), b.(*v1beta2.RemediationStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RemediationStrategy)(nil), (*RemediationStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(a.(*v1beta2.RemediationStrategy), b.(*RemediationStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpdate)(nil), (*v1beta2.RollingUpdate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpdate_To_v1beta2_RollingUpdate(a.(*RollingUpdate), b.(*v1beta2.RollingUpdate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RollingUpdate)(nil), (*RollingUpdate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RollingUpdate_To_v1beta1_RollingUpdate(a.(*v1beta2.RollingUpdate), b.(*RollingUpdate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RolloutStrategy)(nil), (*v1beta2.RolloutStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RolloutStrategy_To_v1beta2_RolloutStrategy(a.(*RolloutStrategy), b.(*v1beta2.RolloutStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RolloutStrategy)(nil), (*RolloutStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RolloutStrategy_To_v1beta1_RolloutStrategy(a.(*v1beta2.RolloutStrategy), b.(*RolloutStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretsEncryption)(nil), (*v1beta2.SecretsEncryption)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretsEncryption_To_v1beta2_SecretsEncryption(a.(*SecretsEncryption), b.(*v1beta2.SecretsEncryption), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.SecretsEncryption)(nil), (*SecretsEncryption)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_SecretsEncryption_To_v1beta1_SecretsEncryption(a.(*v1beta2.SecretsEncryption), b.(*SecretsEncryption), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*corev1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1beta1_Condition(a.(*v1.Condition), b.(*corev1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1_Condition(a.(*corev1beta1.Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.ObjectMeta)(nil), (*corev1beta2.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(a.(*corev1beta1.ObjectMeta), b.(*corev1beta2.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta1.RKE2ConfigSpec)(nil), (*apiv1beta2.RKE2ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigSpec_To_v1beta2_RKE2ConfigSpec(a.(*apiv1beta1.RKE2ConfigSpec), b.(*apiv1beta2.RKE2ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2ControlPlaneMachineTemplate)(nil), (*v1beta2.RKE2ControlPlaneMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneMachineTemplate_To_v1beta2_RKE2ControlPlaneMachineTemplate(a.(*RKE2ControlPlaneMachineTemplate), b.(*v1beta2.RKE2ControlPlaneMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2ControlPlaneSpec)(nil), (*v1beta2.RKE2ControlPlaneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneSpec_To_v1beta2_RKE2ControlPlaneSpec(a.(*RKE2ControlPlaneSpec), b.(*v1beta2.RKE2ControlPlaneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2ControlPlaneStatus)(nil), (*v1beta2.RKE2ControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneStatus_To_v1beta2_RKE2ControlPlaneStatus(a.(*RKE2ControlPlaneStatus), b.(*v1beta2.RKE2ControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2ControlPlaneTemplate)(nil), (*v1beta2.RKE2ControlPlaneTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ControlPlaneTemplate_To_v1beta2_RKE2ControlPlaneTemplate(a.(*RKE2ControlPlaneTemplate), b.(*v1beta2.RKE2ControlPlaneTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta2.ObjectMeta)(nil), (*corev1beta1.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(a.(*corev1beta2.ObjectMeta), b.(*corev1beta1.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta2.RKE2ConfigSpec)(nil), (*apiv1beta1.RKE2ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigSpec_To_v1beta1_RKE2ConfigSpec(a.(*apiv1beta2.RKE2ConfigSpec), b.(*apiv1beta1.RKE2ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.RKE2ControlPlaneMachineTemplate)(nil), (*RKE2ControlPlaneMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneMachineTemplate_To_v1beta1_RKE2ControlPlaneMachineTemplate(a.(*v1beta2.RKE2ControlPlaneMachineTemplate), b.(*RKE2ControlPlaneMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.RKE2ControlPlaneSpec)(nil), (*RKE2ControlPlaneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneSpec_To_v1beta1_RKE2ControlPlaneSpec(a.(*v1beta2.RKE2ControlPlaneSpec), b.(*RKE2ControlPlaneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.RKE2ControlPlaneStatus)(nil), (*RKE2ControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ControlPlaneStatus_To_v1beta1_RKE2ControlPlaneStatus(a.(*v1beta2.RKE2ControlPlaneStatus), b.(*RKE2ControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_DisableComponents_To_v1beta2_DisableComponents(in *DisableComponents, out *v1beta2.DisableComponents, s conversion.Scope) error {
	out.KubernetesComponents = *(*[]v1beta2.DisabledKubernetesComponent)(unsafe.Pointer(&in.KubernetesComponents))
	out.PluginComponents = *(*[]v1beta2.DisabledPluginComponent)(unsafe.Pointer(&in.PluginComponents))
	return nil
}

// Convert_v1beta1_DisableComponents_To_v1beta2_DisableComponents is an autogenerated conversion function.
func Convert_v1beta1_DisableComponents_To_v1beta2_DisableComponents(in *DisableComponents, out *v1beta2.DisableComponents, s conversion.Scope) error {
	return autoConvert_v1beta1_DisableComponents_To_v1beta2_DisableComponents(in, out, s)
}

func autoConvert_v1beta2_DisableComponents_To_v1beta1_DisableComponents(in *v1beta2.DisableComponents, out *DisableComponents, s conversion.Scope) error {
	out.KubernetesComponents = *(*[]DisabledKubernetesComponent)(unsafe.Pointer(&in.KubernetesComponents))
	out.PluginComponents = *(*[]DisabledPluginComponent)(unsafe.Pointer(&in.PluginComponents))
	return nil
}

// Convert_v1beta2_DisableComponents_To_v1beta1_DisableComponents is an autogenerated conversion function.
func Convert_v1beta2_DisableComponents_To_v1beta1_DisableComponents(in *v1beta2.DisableComponents, out *DisableComponents, s conversion.Scope) error {
	return autoConvert_v1beta2_DisableComponents_To_v1beta1_DisableComponents(in, out, s)
}

func autoConvert_v1beta1_EtcdBackupConfig_To_v1beta2_EtcdBackupConfig(in *EtcdBackupConfig, out *v1beta2.EtcdBackupConfig, s conversion.Scope) error {
	out.DisableAutomaticSnapshots = (*bool)(unsafe.Pointer(in.DisableAutomaticSnapshots))
	out.SnapshotName = in.SnapshotName
	out.ScheduleCron = in.ScheduleCron
	out.Retention = in.Retention
	out.Directory = in.Directory
	out.S3 = (*v1beta2.EtcdS3)(unsafe.Pointer(in.S3))
	return nil
}

// Convert_v1beta1_EtcdBackupConfig_To_v1beta2_EtcdBackupConfig is an autogenerated conversion function.
func Convert_v1beta1_EtcdBackupConfig_To_v1beta2_EtcdBackupConfig(in *EtcdBackupConfig, out *v1beta2.EtcdBackupConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdBackupConfig_To_v1beta2_EtcdBackupConfig(in, out, s)
}

func autoConvert_v1beta2_EtcdBackupConfig_To_v1beta1_EtcdBackupConfig(in *v1beta2.EtcdBackupConfig, out *EtcdBackupConfig, s conversion.Scope) error {
	out.DisableAutomaticSnapshots = (*bool)(unsafe.Pointer(in.DisableAutomaticSnapshots))
	out.SnapshotName = in.SnapshotName
	out.ScheduleCron = in.ScheduleCron
	out.Retention = in.Retention
	out.Directory = in.Directory
	out.S3 = (*EtcdS3)(unsafe.Pointer(in.S3))
	return nil
}

// Convert_v1beta2_EtcdBackupConfig_To_v1beta1_EtcdBackupConfig is an autogenerated conversion function.
func Convert_v1beta2_EtcdBackupConfig_To_v1beta1_EtcdBackupConfig(in *v1beta2.EtcdBackupConfig, out *EtcdBackupConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_EtcdBackupConfig_To_v1beta1_EtcdBackupConfig(in, out, s)
}

func autoConvert_v1beta1_EtcdConfig_To_v1beta2_EtcdConfig(in *EtcdConfig, out *v1beta2.EtcdConfig, s conversion.Scope) error {
	out.ExposeMetrics = in.ExposeMetrics
	if err := Convert_v1beta1_EtcdBackupConfig_To_v1beta2_EtcdBackupConfig(&in.BackupConfig, &out.BackupConfig, s); err != nil {
		return err
	}
	out.CustomConfig = (*apiv1beta2.ComponentConfig)(unsafe.Pointer(in.CustomConfig))
	return nil
}

// Convert_v1beta1_EtcdConfig_To_v1beta2_EtcdConfig is an autogenerated conversion function.
func Convert_v1beta1_EtcdConfig_To_v1beta2_EtcdConfig(in *EtcdConfig, out *v1beta2.EtcdConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdConfig_To_v1beta2_EtcdConfig(in, out, s)
}

func autoConvert_v1beta2_EtcdConfig_To_v1beta1_EtcdConfig(in *v1beta2.EtcdConfig, out *EtcdConfig, s conversion.Scope) error {
	out.ExposeMetrics = in.ExposeMetrics
	if err := Convert_v1beta2_EtcdBackupConfig_To_v1beta1_EtcdBackupConfig(&in.BackupConfig, &out.BackupConfig, s); err != nil {
		return err
	}
	out.CustomConfig = (*apiv1beta1.ComponentConfig)(unsafe.Pointer(in.CustomConfig))
	return nil
}

// Convert_v1beta2_EtcdConfig_To_v1beta1_EtcdConfig is an autogenerated conversion function.
func Convert_v1beta2_EtcdConfig_To_v1beta1_EtcdConfig(in *v1beta2.EtcdConfig, out *EtcdConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_EtcdConfig_To_v1beta1_EtcdConfig(in, out, s)
}

func autoConvert_v1beta1_EtcdS3_To_v1beta2_EtcdS3(in *EtcdS3, out *v1beta2.EtcdS3, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.EndpointCASecret = (*corev1.ObjectReference)(unsafe.Pointer(in.EndpointCASecret))
	out.EnforceSSLVerify = in.EnforceSSLVerify
	out.S3CredentialSecret = (*corev1.ObjectReference)(unsafe.Pointer(in.S3CredentialSecret))
	out.Bucket = in.Bucket
	out.Region = in.Region
	out.Folder = in.Folder
	return nil
}

// Convert_v1beta1_EtcdS3_To_v1beta2_EtcdS3 is an autogenerated conversion function.
func Convert_v1beta1_EtcdS3_To_v1beta2_EtcdS3(in *EtcdS3, out *v1beta2.EtcdS3, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdS3_To_v1beta2_EtcdS3(in, out, s)
}

func autoConvert_v1beta2_EtcdS3_To_v1beta1_EtcdS3(in *v1beta2.EtcdS3, out *EtcdS3, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.EndpointCASecret = (*corev1.ObjectReference)(unsafe.Pointer(in.EndpointCASecret))
	out.EnforceSSLVerify = in.EnforceSSLVerify
	out.S3CredentialSecret = (*corev1.ObjectReference)(unsafe.Pointer(in.S3CredentialSecret))
	out.Bucket = in.Bucket
	out.Region = in.Region
	out.Folder = in.Folder
	return nil
}

// Convert_v1beta2_EtcdS3_To_v1beta1_EtcdS3 is an autogenerated conversion function.
func Convert_v1beta2_EtcdS3_To_v1beta1_EtcdS3(in *v1beta2.EtcdS3, out *EtcdS3, s conversion.Scope) error {
	return autoConvert_v1beta2_EtcdS3_To_v1beta1_EtcdS3(in, out, s)
}

func autoConvert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(in *LastRemediationStatus, out *v1beta2.LastRemediationStatus, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Timestamp = in.Timestamp
	out.RetryCount = in.RetryCount
	return nil
}

// Convert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus is an autogenerated conversion function.
func Convert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(in *LastRemediationStatus, out *v1beta2.LastRemediationStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_LastRemediationStatus_To_v1beta2_LastRemediationStatus(in, out, s)
}

func autoConvert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(in *v1beta2.LastRemediationStatus, out *LastRemediationStatus, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Timestamp = in.Timestamp
	out.RetryCount = in.RetryCount
	return nil
}

// Convert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus is an autogenerated conversion function.
func Convert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(in *v1beta2.LastRemediationStatus, out *LastRemediationStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_LastRemediationStatus_To_v1beta1_LastRemediationStatus(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlane_To_v1beta2_RKE2ControlPlane(in *RKE2ControlPlane, out *v1beta2.RKE2ControlPlane, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RKE2ControlPlaneSpec_To_v1beta2_RKE2ControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RKE2ControlPlaneStatus_To_v1beta2_RKE2ControlPlaneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2ControlPlane_To_v1beta2_RKE2ControlPlane is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlane_To_v1beta2_RKE2ControlPlane(in *RKE2ControlPlane, out *v1beta2.RKE2ControlPlane, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlane_To_v1beta2_RKE2ControlPlane(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlane_To_v1beta1_RKE2ControlPlane(in *v1beta2.RKE2ControlPlane, out *RKE2ControlPlane, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_RKE2ControlPlaneSpec_To_v1beta1_RKE2ControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_RKE2ControlPlaneStatus_To_v1beta1_RKE2ControlPlaneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ControlPlane_To_v1beta1_RKE2ControlPlane is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlane_To_v1beta1_RKE2ControlPlane(in *v1beta2.RKE2ControlPlane, out *RKE2ControlPlane, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlane_To_v1beta1_RKE2ControlPlane(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneCustomDefaulter_To_v1beta2_RKE2ControlPlaneCustomDefaulter(in *RKE2ControlPlaneCustomDefaulter, out *v1beta2.RKE2ControlPlaneCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneCustomDefaulter_To_v1beta2_RKE2ControlPlaneCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneCustomDefaulter_To_v1beta2_RKE2ControlPlaneCustomDefaulter(in *RKE2ControlPlaneCustomDefaulter, out *v1beta2.RKE2ControlPlaneCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneCustomDefaulter_To_v1beta2_RKE2ControlPlaneCustomDefaulter(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneCustomDefaulter_To_v1beta1_RKE2ControlPlaneCustomDefaulter(in *v1beta2.RKE2ControlPlaneCustomDefaulter, out *RKE2ControlPlaneCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneCustomDefaulter_To_v1beta1_RKE2ControlPlaneCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneCustomDefaulter_To_v1beta1_RKE2ControlPlaneCustomDefaulter(in *v1beta2.RKE2ControlPlaneCustomDefaulter, out *RKE2ControlPlaneCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneCustomDefaulter_To_v1beta1_RKE2ControlPlaneCustomDefaulter(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneCustomValidator_To_v1beta2_RKE2ControlPlaneCustomValidator(in *RKE2ControlPlaneCustomValidator, out *v1beta2.RKE2ControlPlaneCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneCustomValidator_To_v1beta2_RKE2ControlPlaneCustomValidator is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneCustomValidator_To_v1beta2_RKE2ControlPlaneCustomValidator(in *RKE2ControlPlaneCustomValidator, out *v1beta2.RKE2ControlPlaneCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneCustomValidator_To_v1beta2_RKE2ControlPlaneCustomValidator(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneCustomValidator_To_v1beta1_RKE2ControlPlaneCustomValidator(in *v1beta2.RKE2ControlPlaneCustomValidator, out *RKE2ControlPlaneCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneCustomValidator_To_v1beta1_RKE2ControlPlaneCustomValidator is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneCustomValidator_To_v1beta1_RKE2ControlPlaneCustomValidator(in *v1beta2.RKE2ControlPlaneCustomValidator, out *RKE2ControlPlaneCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneCustomValidator_To_v1beta1_RKE2ControlPlaneCustomValidator(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneList_To_v1beta2_RKE2ControlPlaneList(in *RKE2ControlPlaneList, out *v1beta2.RKE2ControlPlaneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.RKE2ControlPlane, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_RKE2ControlPlane_To_v1beta2_RKE2ControlPlane(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneList_To_v1beta2_RKE2ControlPlaneList is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneList_To_v1beta2_RKE2ControlPlaneList(in *RKE2ControlPlaneList, out *v1beta2.RKE2ControlPlaneList, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneList_To_v1beta2_RKE2ControlPlaneList(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneList_To_v1beta1_RKE2ControlPlaneList(in *v1beta2.RKE2ControlPlaneList, out *RKE2ControlPlaneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RKE2ControlPlane, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_RKE2ControlPlane_To_v1beta1_RKE2ControlPlane(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneList_To_v1beta1_RKE2ControlPlaneList is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneList_To_v1beta1_RKE2ControlPlaneList(in *v1beta2.RKE2ControlPlaneList, out *RKE2ControlPlaneList, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneList_To_v1beta1_RKE2ControlPlaneList(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneMachineTemplate_To_v1beta2_RKE2ControlPlaneMachineTemplate(in *RKE2ControlPlaneMachineTemplate, out *v1beta2.RKE2ControlPlaneMachineTemplate, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	// WARNING: in.InfrastructureRef requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeDrainTimeout requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeVolumeDetachTimeout requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeDeletionTimeout requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_RKE2ControlPlaneMachineTemplate_To_v1beta1_RKE2ControlPlaneMachineTemplate(in *v1beta2.RKE2ControlPlaneMachineTemplate, out *RKE2ControlPlaneMachineTemplate, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	// WARNING: in.Spec requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_RKE2ControlPlaneSpec_To_v1beta2_RKE2ControlPlaneSpec(in *RKE2ControlPlaneSpec, out *v1beta2.RKE2ControlPlaneSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_RKE2ConfigSpec_To_v1beta2_RKE2ConfigSpec(&in.RKE2ConfigSpec, &out.RKE2ConfigSpec, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Version = in.Version
	if err := Convert_v1beta1_RKE2ControlPlaneMachineTemplate_To_v1beta2_RKE2ControlPlaneMachineTemplate(&in.MachineTemplate, &out.MachineTemplate, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RKE2ServerConfig_To_v1beta2_RKE2ServerConfig(&in.ServerConfig, &out.ServerConfig, s); err != nil {
		return err
	}
	out.ManifestsConfigMapReference = in.ManifestsConfigMapReference
	// WARNING: in.InfrastructureRef requires manual conversion: does not exist in peer-type
	// WARNING: in.NodeDrainTimeout requires manual conversion: does not exist in peer-type
	out.RegistrationMethod = v1beta2.RegistrationMethod(in.RegistrationMethod)
	out.RegistrationAddress = in.RegistrationAddress
	out.RolloutStrategy = (*v1beta2.RolloutStrategy)(unsafe.Pointer(in.RolloutStrategy))
	out.RemediationStrategy = (*v1beta2.RemediationStrategy)(unsafe.Pointer(in.RemediationStrategy))
	return nil
}

func autoConvert_v1beta2_RKE2ControlPlaneSpec_To_v1beta1_RKE2ControlPlaneSpec(in *v1beta2.RKE2ControlPlaneSpec, out *RKE2ControlPlaneSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_RKE2ConfigSpec_To_v1beta1_RKE2ConfigSpec(&in.RKE2ConfigSpec, &out.RKE2ConfigSpec, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Version = in.Version
	if err := Convert_v1beta2_RKE2ControlPlaneMachineTemplate_To_v1beta1_RKE2ControlPlaneMachineTemplate(&in.MachineTemplate, &out.MachineTemplate, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_RKE2ServerConfig_To_v1beta1_RKE2ServerConfig(&in.ServerConfig, &out.ServerConfig, s); err != nil {
		return err
	}
	out.ManifestsConfigMapReference = in.ManifestsConfigMapReference
	out.RegistrationMethod = RegistrationMethod(in.RegistrationMethod)
	out.RegistrationAddress = in.RegistrationAddress
	out.RolloutStrategy = (*RolloutStrategy)(unsafe.Pointer(in.RolloutStrategy))
	out.RemediationStrategy = (*RemediationStrategy)(unsafe.Pointer(in.RemediationStrategy))
	return nil
}

func autoConvert_v1beta1_RKE2ControlPlaneStatus_To_v1beta2_RKE2ControlPlaneStatus(in *RKE2ControlPlaneStatus, out *v1beta2.RKE2ControlPlaneStatus, s conversion.Scope) error {
	// WARNING: in.Ready requires manual conversion: does not exist in peer-type
	// WARNING: in.Initialized requires manual conversion: does not exist in peer-type
	// WARNING: in.DataSecretName requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	if err := v1.Convert_int32_To_Pointer_int32(&in.Replicas, &out.Replicas, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.Version, &out.Version, s); err != nil {
		return err
	}
	if err := v1.Convert_int32_To_Pointer_int32(&in.ReadyReplicas, &out.ReadyReplicas, s); err != nil {
		return err
	}
	// WARNING: in.UpdatedReplicas requires manual conversion: does not exist in peer-type
	// WARNING: in.UnavailableReplicas requires manual conversion: does not exist in peer-type
	out.AvailableServerIPs = *(*[]string)(unsafe.Pointer(&in.AvailableServerIPs))
	out.LastRemediation = (*v1beta2.LastRemediationStatus)(unsafe.Pointer(in.LastRemediation))
	// WARNING: in.V1Beta2 requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_RKE2ControlPlaneStatus_To_v1beta1_RKE2ControlPlaneStatus(in *v1beta2.RKE2ControlPlaneStatus, out *RKE2ControlPlaneStatus, s conversion.Scope) error {
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.Initialization requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	if err := v1.Convert_Pointer_int32_To_int32(&in.Replicas, &out.Replicas, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.Version, &out.Version, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_int32_To_int32(&in.ReadyReplicas, &out.ReadyReplicas, s); err != nil {
		return err
	}
	// WARNING: in.AvailableReplicas requires manual conversion: does not exist in peer-type
	// WARNING: in.UpToDateReplicas requires manual conversion: does not exist in peer-type
	out.AvailableServerIPs = *(*[]string)(unsafe.Pointer(&in.AvailableServerIPs))
	out.LastRemediation = (*LastRemediationStatus)(unsafe.Pointer(in.LastRemediation))
	// WARNING: in.Deprecated requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_RKE2ControlPlaneTemplate_To_v1beta2_RKE2ControlPlaneTemplate(in *RKE2ControlPlaneTemplate, out *v1beta2.RKE2ControlPlaneTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RKE2ControlPlaneTemplateSpec_To_v1beta2_RKE2ControlPlaneTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	// WARNING: in.Status requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_RKE2ControlPlaneTemplate_To_v1beta1_RKE2ControlPlaneTemplate(in *v1beta2.RKE2ControlPlaneTemplate, out *RKE2ControlPlaneTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_RKE2ControlPlaneTemplateSpec_To_v1beta1_RKE2ControlPlaneTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneTemplate_To_v1beta1_RKE2ControlPlaneTemplate is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneTemplate_To_v1beta1_RKE2ControlPlaneTemplate(in *v1beta2.RKE2ControlPlaneTemplate, out *RKE2ControlPlaneTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneTemplate_To_v1beta1_RKE2ControlPlaneTemplate(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter(in *RKE2ControlPlaneTemplateCustomDefaulter, out *v1beta2.RKE2ControlPlaneTemplateCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter(in *RKE2ControlPlaneTemplateCustomDefaulter, out *v1beta2.RKE2ControlPlaneTemplateCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter(in *v1beta2.RKE2ControlPlaneTemplateCustomDefaulter, out *RKE2ControlPlaneTemplateCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter(in *v1beta2.RKE2ControlPlaneTemplateCustomDefaulter, out *RKE2ControlPlaneTemplateCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneTemplateCustomDefaulter_To_v1beta1_RKE2ControlPlaneTemplateCustomDefaulter(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneTemplateCustomValidator_To_v1beta2_RKE2ControlPlaneTemplateCustomValidator(in *RKE2ControlPlaneTemplateCustomValidator, out *v1beta2.RKE2ControlPlaneTemplateCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneTemplateCustomValidator_To_v1beta2_RKE2ControlPlaneTemplateCustomValidator is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneTemplateCustomValidator_To_v1beta2_RKE2ControlPlaneTemplateCustomValidator(in *RKE2ControlPlaneTemplateCustomValidator, out *v1beta2.RKE2ControlPlaneTemplateCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneTemplateCustomValidator_To_v1beta2_RKE2ControlPlaneTemplateCustomValidator(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneTemplateCustomValidator_To_v1beta1_RKE2ControlPlaneTemplateCustomValidator(in *v1beta2.RKE2ControlPlaneTemplateCustomValidator, out *RKE2ControlPlaneTemplateCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneTemplateCustomValidator_To_v1beta1_RKE2ControlPlaneTemplateCustomValidator is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneTemplateCustomValidator_To_v1beta1_RKE2ControlPlaneTemplateCustomValidator(in *v1beta2.RKE2ControlPlaneTemplateCustomValidator, out *RKE2ControlPlaneTemplateCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneTemplateCustomValidator_To_v1beta1_RKE2ControlPlaneTemplateCustomValidator(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneTemplateList_To_v1beta2_RKE2ControlPlaneTemplateList(in *RKE2ControlPlaneTemplateList, out *v1beta2.RKE2ControlPlaneTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.RKE2ControlPlaneTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_RKE2ControlPlaneTemplate_To_v1beta2_RKE2ControlPlaneTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneTemplateList_To_v1beta2_RKE2ControlPlaneTemplateList is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneTemplateList_To_v1beta2_RKE2ControlPlaneTemplateList(in *RKE2ControlPlaneTemplateList, out *v1beta2.RKE2ControlPlaneTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneTemplateList_To_v1beta2_RKE2ControlPlaneTemplateList(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneTemplateList_To_v1beta1_RKE2ControlPlaneTemplateList(in *v1beta2.RKE2ControlPlaneTemplateList, out *RKE2ControlPlaneTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RKE2ControlPlaneTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_RKE2ControlPlaneTemplate_To_v1beta1_RKE2ControlPlaneTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneTemplateList_To_v1beta1_RKE2ControlPlaneTemplateList is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneTemplateList_To_v1beta1_RKE2ControlPlaneTemplateList(in *v1beta2.RKE2ControlPlaneTemplateList, out *RKE2ControlPlaneTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneTemplateList_To_v1beta1_RKE2ControlPlaneTemplateList(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneTemplateResource_To_v1beta2_RKE2ControlPlaneTemplateResource(in *RKE2ControlPlaneTemplateResource, out *v1beta2.RKE2ControlPlaneTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_RKE2ControlPlaneSpec_To_v1beta2_RKE2ControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneTemplateResource_To_v1beta2_RKE2ControlPlaneTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneTemplateResource_To_v1beta2_RKE2ControlPlaneTemplateResource(in *RKE2ControlPlaneTemplateResource, out *v1beta2.RKE2ControlPlaneTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneTemplateResource_To_v1beta2_RKE2ControlPlaneTemplateResource(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneTemplateResource_To_v1beta1_RKE2ControlPlaneTemplateResource(in *v1beta2.RKE2ControlPlaneTemplateResource, out *RKE2ControlPlaneTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_RKE2ControlPlaneSpec_To_v1beta1_RKE2ControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneTemplateResource_To_v1beta1_RKE2ControlPlaneTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneTemplateResource_To_v1beta1_RKE2ControlPlaneTemplateResource(in *v1beta2.RKE2ControlPlaneTemplateResource, out *RKE2ControlPlaneTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneTemplateResource_To_v1beta1_RKE2ControlPlaneTemplateResource(in, out, s)
}

func autoConvert_v1beta1_RKE2ControlPlaneTemplateSpec_To_v1beta2_RKE2ControlPlaneTemplateSpec(in *RKE2ControlPlaneTemplateSpec, out *v1beta2.RKE2ControlPlaneTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_RKE2ControlPlaneTemplateResource_To_v1beta2_RKE2ControlPlaneTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2ControlPlaneTemplateSpec_To_v1beta2_RKE2ControlPlaneTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_RKE2ControlPlaneTemplateSpec_To_v1beta2_RKE2ControlPlaneTemplateSpec(in *RKE2ControlPlaneTemplateSpec, out *v1beta2.RKE2ControlPlaneTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ControlPlaneTemplateSpec_To_v1beta2_RKE2ControlPlaneTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_RKE2ControlPlaneTemplateSpec_To_v1beta1_RKE2ControlPlaneTemplateSpec(in *v1beta2.RKE2ControlPlaneTemplateSpec, out *RKE2ControlPlaneTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_RKE2ControlPlaneTemplateResource_To_v1beta1_RKE2ControlPlaneTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ControlPlaneTemplateSpec_To_v1beta1_RKE2ControlPlaneTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_RKE2ControlPlaneTemplateSpec_To_v1beta1_RKE2ControlPlaneTemplateSpec(in *v1beta2.RKE2ControlPlaneTemplateSpec, out *RKE2ControlPlaneTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ControlPlaneTemplateSpec_To_v1beta1_RKE2ControlPlaneTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_RKE2ServerConfig_To_v1beta2_RKE2ServerConfig(in *RKE2ServerConfig, out *v1beta2.RKE2ServerConfig, s conversion.Scope) error {
	out.AuditPolicySecret = (*corev1.ObjectReference)(unsafe.Pointer(in.AuditPolicySecret))
	out.BindAddress = in.BindAddress
	out.AdvertiseAddress = in.AdvertiseAddress
	out.TLSSan = *(*[]string)(unsafe.Pointer(&in.TLSSan))
	out.ServiceNodePortRange = in.ServiceNodePortRange
	out.ClusterDNS = in.ClusterDNS
	out.ClusterDomain = in.ClusterDomain
	if err := Convert_v1beta1_DisableComponents_To_v1beta2_DisableComponents(&in.DisableComponents, &out.DisableComponents, s); err != nil {
		return err
	}
	out.CNI = v1beta2.CNI(in.CNI)
	out.CNIMultusEnable = in.CNIMultusEnable
	out.PauseImage = in.PauseImage
	if err := Convert_v1beta1_EtcdConfig_To_v1beta2_EtcdConfig(&in.Etcd, &out.Etcd, s); err != nil {
		return err
	}
	out.SecretsEncryptionProvider = (*v1beta2.SecretsEncryption)(unsafe.Pointer(in.SecretsEncryptionProvider))
	out.KubeAPIServer = (*apiv1beta2.ComponentConfig)(unsafe.Pointer(in.KubeAPIServer))
	out.KubeControllerManager = (*apiv1beta2.ComponentConfig)(unsafe.Pointer(in.KubeControllerManager))
	out.KubeScheduler = (*apiv1beta2.ComponentConfig)(unsafe.Pointer(in.KubeScheduler))
	out.CloudControllerManager = (*apiv1beta2.ComponentConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.CloudProviderName = in.CloudProviderName
	out.CloudProviderConfigMap = (*corev1.ObjectReference)(unsafe.Pointer(in.CloudProviderConfigMap))
	out.EmbeddedRegistry = in.EmbeddedRegistry
	out.ExternalDatastoreSecret = (*corev1.ObjectReference)(unsafe.Pointer(in.ExternalDatastoreSecret))
	return nil
}

// Convert_v1beta1_RKE2ServerConfig_To_v1beta2_RKE2ServerConfig is an autogenerated conversion function.
func Convert_v1beta1_RKE2ServerConfig_To_v1beta2_RKE2ServerConfig(in *RKE2ServerConfig, out *v1beta2.RKE2ServerConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ServerConfig_To_v1beta2_RKE2ServerConfig(in, out, s)
}

func autoConvert_v1beta2_RKE2ServerConfig_To_v1beta1_RKE2ServerConfig(in *v1beta2.RKE2ServerConfig, out *RKE2ServerConfig, s conversion.Scope) error {
	out.AuditPolicySecret = (*corev1.ObjectReference)(unsafe.Pointer(in.AuditPolicySecret))
	out.BindAddress = in.BindAddress
	out.AdvertiseAddress = in.AdvertiseAddress
	out.TLSSan = *(*[]string)(unsafe.Pointer(&in.TLSSan))
	out.ServiceNodePortRange = in.ServiceNodePortRange
	out.ClusterDNS = in.ClusterDNS
	out.ClusterDomain = in.ClusterDomain
	if err := Convert_v1beta2_DisableComponents_To_v1beta1_DisableComponents(&in.DisableComponents, &out.DisableComponents, s); err != nil {
		return err
	}
	out.CNI = CNI(in.CNI)
	out.CNIMultusEnable = in.CNIMultusEnable
	out.PauseImage = in.PauseImage
	if err := Convert_v1beta2_EtcdConfig_To_v1beta1_EtcdConfig(&in.Etcd, &out.Etcd, s); err != nil {
		return err
	}
	out.SecretsEncryptionProvider = (*SecretsEncryption)(unsafe.Pointer(in.SecretsEncryptionProvider))
	out.KubeAPIServer = (*apiv1beta1.ComponentConfig)(unsafe.Pointer(in.KubeAPIServer))
	out.KubeControllerManager = (*apiv1beta1.ComponentConfig)(unsafe.Pointer(in.KubeControllerManager))
	out.KubeScheduler = (*apiv1beta1.ComponentConfig)(unsafe.Pointer(in.KubeScheduler))
	out.CloudControllerManager = (*apiv1beta1.ComponentConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.CloudProviderName = in.CloudProviderName
	out.CloudProviderConfigMap = (*corev1.ObjectReference)(unsafe.Pointer(in.CloudProviderConfigMap))
	out.EmbeddedRegistry = in.EmbeddedRegistry
	out.ExternalDatastoreSecret = (*corev1.ObjectReference)(unsafe.Pointer(in.ExternalDatastoreSecret))
	return nil
}

// Convert_v1beta2_RKE2ServerConfig_To_v1beta1_RKE2ServerConfig is an autogenerated conversion function.
func Convert_v1beta2_RKE2ServerConfig_To_v1beta1_RKE2ServerConfig(in *v1beta2.RKE2ServerConfig, out *RKE2ServerConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ServerConfig_To_v1beta1_RKE2ServerConfig(in, out, s)
}

func autoConvert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in *RemediationStrategy, out *v1beta2.RemediationStrategy, s conversion.Scope) error {
	out.MaxRetry = (*int32)(unsafe.Pointer(in.MaxRetry))
	out.RetryPeriod = in.RetryPeriod
	out.MinHealthyPeriod = (*v1.Duration)(unsafe.Pointer(in.MinHealthyPeriod))
	return nil
}

// Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy is an autogenerated conversion function.
func Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in *RemediationStrategy, out *v1beta2.RemediationStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in, out, s)
}

func autoConvert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in *v1beta2.RemediationStrategy, out *RemediationStrategy, s conversion.Scope) error {
	out.MaxRetry = (*int32)(unsafe.Pointer(in.MaxRetry))
	out.RetryPeriod = in.RetryPeriod
	out.MinHealthyPeriod = (*v1.Duration)(unsafe.Pointer(in.MinHealthyPeriod))
	return nil
}

// Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy is an autogenerated conversion function.
func Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in *v1beta2.RemediationStrategy, out *RemediationStrategy, s conversion.Scope) error {
	return autoConvert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in, out, s)
}

func autoConvert_v1beta1_RollingUpdate_To_v1beta2_RollingUpdate(in *RollingUpdate, out *v1beta2.RollingUpdate, s conversion.Scope) error {
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_v1beta1_RollingUpdate_To_v1beta2_RollingUpdate is an autogenerated conversion function.
func Convert_v1beta1_RollingUpdate_To_v1beta2_RollingUpdate(in *RollingUpdate, out *v1beta2.RollingUpdate, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpdate_To_v1beta2_RollingUpdate(in, out, s)
}

func autoConvert_v1beta2_RollingUpdate_To_v1beta1_RollingUpdate(in *v1beta2.RollingUpdate, out *RollingUpdate, s conversion.Scope) error {
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_v1beta2_RollingUpdate_To_v1beta1_RollingUpdate is an autogenerated conversion function.
func Convert_v1beta2_RollingUpdate_To_v1beta1_RollingUpdate(in *v1beta2.RollingUpdate, out *RollingUpdate, s conversion.Scope) error {
	return autoConvert_v1beta2_RollingUpdate_To_v1beta1_RollingUpdate(in, out, s)
}

func autoConvert_v1beta1_RolloutStrategy_To_v1beta2_RolloutStrategy(in *RolloutStrategy, out *v1beta2.RolloutStrategy, s conversion.Scope) error {
	out.Type = v1beta2.RolloutStrategyType(in.Type)
	out.RollingUpdate = (*v1beta2.RollingUpdate)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_v1beta1_RolloutStrategy_To_v1beta2_RolloutStrategy is an autogenerated conversion function.
func Convert_v1beta1_RolloutStrategy_To_v1beta2_RolloutStrategy(in *RolloutStrategy, out *v1beta2.RolloutStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_RolloutStrategy_To_v1beta2_RolloutStrategy(in, out, s)
}

func autoConvert_v1beta2_RolloutStrategy_To_v1beta1_RolloutStrategy(in *v1beta2.RolloutStrategy, out *RolloutStrategy, s conversion.Scope) error {
	out.Type = RolloutStrategyType(in.Type)
	out.RollingUpdate = (*RollingUpdate)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_v1beta2_RolloutStrategy_To_v1beta1_RolloutStrategy is an autogenerated conversion function.
func Convert_v1beta2_RolloutStrategy_To_v1beta1_RolloutStrategy(in *v1beta2.RolloutStrategy, out *RolloutStrategy, s conversion.Scope) error {
	return autoConvert_v1beta2_RolloutStrategy_To_v1beta1_RolloutStrategy(in, out, s)
}

func autoConvert_v1beta1_SecretsEncryption_To_v1beta2_SecretsEncryption(in *SecretsEncryption, out *v1beta2.SecretsEncryption, s conversion.Scope) error {
	out.EncryptionKeySecret = (*corev1.ObjectReference)(unsafe.Pointer(in.EncryptionKeySecret))
	out.Provider = in.Provider
	return nil
}

// Convert_v1beta1_SecretsEncryption_To_v1beta2_SecretsEncryption is an autogenerated conversion function.
func Convert_v1beta1_SecretsEncryption_To_v1beta2_SecretsEncryption(in *SecretsEncryption, out *v1beta2.SecretsEncryption, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretsEncryption_To_v1beta2_SecretsEncryption(in, out, s)
}

func autoConvert_v1beta2_SecretsEncryption_To_v1beta1_SecretsEncryption(in *v1beta2.SecretsEncryption, out *SecretsEncryption, s conversion.Scope) error {
	out.EncryptionKeySecret = (*corev1.ObjectReference)(unsafe.Pointer(in.EncryptionKeySecret))
	out.Provider = in.Provider
	return nil
}

// Convert_v1beta2_SecretsEncryption_To_v1beta1_SecretsEncryption is an autogenerated conversion function.
func Convert_v1beta2_SecretsEncryption_To_v1beta1_SecretsEncryption(in *v1beta2.SecretsEncryption, out *SecretsEncryption, s conversion.Scope) error {
	return autoConvert_v1beta2_SecretsEncryption_To_v1beta1_SecretsEncryption(in, out, s)
}
