//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 SUSE LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1beta2 "github.com/rancher/cluster-api-provider-rke2/bootstrap/api/v1beta2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalUserData)(nil), (*v1beta2.AdditionalUserData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AdditionalUserData_To_v1beta2_AdditionalUserData(a.(*AdditionalUserData), b.(*v1beta2.AdditionalUserData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AdditionalUserData)(nil), (*AdditionalUserData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AdditionalUserData_To_v1beta1_AdditionalUserData(a.(*v1beta2.AdditionalUserData), b.(*AdditionalUserData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentConfig)(nil), (*v1beta2.ComponentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ComponentConfig_To_v1beta2_ComponentConfig(a.(*ComponentConfig), b.(*v1beta2.ComponentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ComponentConfig)(nil), (*ComponentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ComponentConfig_To_v1beta1_ComponentConfig(a.(*v1beta2.ComponentConfig), b.(*ComponentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*v1beta2.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_File_To_v1beta2_File(a.(*File), b.(*v1beta2.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_File_To_v1beta1_File(a.(*v1beta2.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSource)(nil), (*v1beta2.FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FileSource_To_v1beta2_FileSource(a.(*FileSource), b.(*v1beta2.FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.FileSource)(nil), (*FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_FileSource_To_v1beta1_FileSource(a.(*v1beta2.FileSource), b.(*FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSourceRef)(nil), (*v1beta2.FileSourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FileSourceRef_To_v1beta2_FileSourceRef(a.(*FileSourceRef), b.(*v1beta2.FileSourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.FileSourceRef)(nil), (*FileSourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_FileSourceRef_To_v1beta1_FileSourceRef(a.(*v1beta2.FileSourceRef), b.(*FileSourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Mirror)(nil), (*v1beta2.Mirror)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Mirror_To_v1beta2_Mirror(a.(*Mirror), b.(*v1beta2.Mirror), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Mirror)(nil), (*Mirror)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Mirror_To_v1beta1_Mirror(a.(*v1beta2.Mirror), b.(*Mirror), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NTP)(nil), (*v1beta2.NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NTP_To_v1beta2_NTP(a.(*NTP), b.(*v1beta2.NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.NTP)(nil), (*NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NTP_To_v1beta1_NTP(a.(*v1beta2.NTP), b.(*NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2Config)(nil), (*v1beta2.RKE2Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2Config_To_v1beta2_RKE2Config(a.(*RKE2Config), b.(*v1beta2.RKE2Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2Config)(nil), (*RKE2Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2Config_To_v1beta1_RKE2Config(a.(*v1beta2.RKE2Config), b.(*RKE2Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigCustomDefaulter)(nil), (*v1beta2.RKE2ConfigCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigCustomDefaulter_To_v1beta2_RKE2ConfigCustomDefaulter(a.(*RKE2ConfigCustomDefaulter), b.(*v1beta2.RKE2ConfigCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigCustomDefaulter)(nil), (*RKE2ConfigCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigCustomDefaulter_To_v1beta1_RKE2ConfigCustomDefaulter(a.(*v1beta2.RKE2ConfigCustomDefaulter), b.(*RKE2ConfigCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigCustomValidator)(nil), (*v1beta2.RKE2ConfigCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigCustomValidator_To_v1beta2_RKE2ConfigCustomValidator(a.(*RKE2ConfigCustomValidator), b.(*v1beta2.RKE2ConfigCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigCustomValidator)(nil), (*RKE2ConfigCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigCustomValidator_To_v1beta1_RKE2ConfigCustomValidator(a.(*v1beta2.RKE2ConfigCustomValidator), b.(*RKE2ConfigCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigList)(nil), (*v1beta2.RKE2ConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigList_To_v1beta2_RKE2ConfigList(a.(*RKE2ConfigList), b.(*v1beta2.RKE2ConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigList)(nil), (*RKE2ConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigList_To_v1beta1_RKE2ConfigList(a.(*v1beta2.RKE2ConfigList), b.(*RKE2ConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplate)(nil), (*v1beta2.RKE2ConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigTemplate_To_v1beta2_RKE2ConfigTemplate(a.(*RKE2ConfigTemplate), b.(*v1beta2.RKE2ConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigTemplate)(nil), (*RKE2ConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigTemplate_To_v1beta1_RKE2ConfigTemplate(a.(*v1beta2.RKE2ConfigTemplate), b.(*RKE2ConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateCustomDefaulter)(nil), (*v1beta2.RKE2ConfigTemplateCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigTemplateCustomDefaulter_To_v1beta2_RKE2ConfigTemplateCustomDefaulter(a.(*RKE2ConfigTemplateCustomDefaulter), b.(*v1beta2.RKE2ConfigTemplateCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigTemplateCustomDefaulter)(nil), (*RKE2ConfigTemplateCustomDefaulter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigTemplateCustomDefaulter_To_v1beta1_RKE2ConfigTemplateCustomDefaulter(a.(*v1beta2.RKE2ConfigTemplateCustomDefaulter), b.(*RKE2ConfigTemplateCustomDefaulter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateCustomValidator)(nil), (*v1beta2.RKE2ConfigTemplateCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigTemplateCustomValidator_To_v1beta2_RKE2ConfigTemplateCustomValidator(a.(*RKE2ConfigTemplateCustomValidator), b.(*v1beta2.RKE2ConfigTemplateCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigTemplateCustomValidator)(nil), (*RKE2ConfigTemplateCustomValidator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigTemplateCustomValidator_To_v1beta1_RKE2ConfigTemplateCustomValidator(a.(*v1beta2.RKE2ConfigTemplateCustomValidator), b.(*RKE2ConfigTemplateCustomValidator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateList)(nil), (*v1beta2.RKE2ConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigTemplateList_To_v1beta2_RKE2ConfigTemplateList(a.(*RKE2ConfigTemplateList), b.(*v1beta2.RKE2ConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigTemplateList)(nil), (*RKE2ConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigTemplateList_To_v1beta1_RKE2ConfigTemplateList(a.(*v1beta2.RKE2ConfigTemplateList), b.(*RKE2ConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateResource)(nil), (*v1beta2.RKE2ConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigTemplateResource_To_v1beta2_RKE2ConfigTemplateResource(a.(*RKE2ConfigTemplateResource), b.(*v1beta2.RKE2ConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigTemplateResource)(nil), (*RKE2ConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigTemplateResource_To_v1beta1_RKE2ConfigTemplateResource(a.(*v1beta2.RKE2ConfigTemplateResource), b.(*RKE2ConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RKE2ConfigTemplateSpec)(nil), (*v1beta2.RKE2ConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigTemplateSpec_To_v1beta2_RKE2ConfigTemplateSpec(a.(*RKE2ConfigTemplateSpec), b.(*v1beta2.RKE2ConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RKE2ConfigTemplateSpec)(nil), (*RKE2ConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigTemplateSpec_To_v1beta1_RKE2ConfigTemplateSpec(a.(*v1beta2.RKE2ConfigTemplateSpec), b.(*RKE2ConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Registry)(nil), (*v1beta2.Registry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Registry_To_v1beta2_Registry(a.(*Registry), b.(*v1beta2.Registry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Registry)(nil), (*Registry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Registry_To_v1beta1_Registry(a.(*v1beta2.Registry), b.(*Registry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegistryConfig)(nil), (*v1beta2.RegistryConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RegistryConfig_To_v1beta2_RegistryConfig(a.(*RegistryConfig), b.(*v1beta2.RegistryConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RegistryConfig)(nil), (*RegistryConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RegistryConfig_To_v1beta1_RegistryConfig(a.(*v1beta2.RegistryConfig), b.(*RegistryConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSConfig)(nil), (*v1beta2.TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TLSConfig_To_v1beta2_TLSConfig(a.(*TLSConfig), b.(*v1beta2.TLSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.TLSConfig)(nil), (*TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_TLSConfig_To_v1beta1_TLSConfig(a.(*v1beta2.TLSConfig), b.(*TLSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*corev1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1beta1_Condition(a.(*v1.Condition), b.(*corev1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1_Condition(a.(*corev1beta1.Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2AgentConfig)(nil), (*v1beta2.RKE2AgentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2AgentConfig_To_v1beta2_RKE2AgentConfig(a.(*RKE2AgentConfig), b.(*v1beta2.RKE2AgentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2ConfigSpec)(nil), (*v1beta2.RKE2ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigSpec_To_v1beta2_RKE2ConfigSpec(a.(*RKE2ConfigSpec), b.(*v1beta2.RKE2ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RKE2ConfigStatus)(nil), (*v1beta2.RKE2ConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RKE2ConfigStatus_To_v1beta2_RKE2ConfigStatus(a.(*RKE2ConfigStatus), b.(*v1beta2.RKE2ConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.RKE2AgentConfig)(nil), (*RKE2AgentConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2AgentConfig_To_v1beta1_RKE2AgentConfig(a.(*v1beta2.RKE2AgentConfig), b.(*RKE2AgentConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.RKE2ConfigSpec)(nil), (*RKE2ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigSpec_To_v1beta1_RKE2ConfigSpec(a.(*v1beta2.RKE2ConfigSpec), b.(*RKE2ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.RKE2ConfigStatus)(nil), (*RKE2ConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RKE2ConfigStatus_To_v1beta1_RKE2ConfigStatus(a.(*v1beta2.RKE2ConfigStatus), b.(*RKE2ConfigStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_AdditionalUserData_To_v1beta2_AdditionalUserData(in *AdditionalUserData, out *v1beta2.AdditionalUserData, s conversion.Scope) error {
	out.Config = in.Config
	out.Data = *(*map[string]string)(unsafe.Pointer(&in.Data))
	out.Strict = in.Strict
	return nil
}

// Convert_v1beta1_AdditionalUserData_To_v1beta2_AdditionalUserData is an autogenerated conversion function.
func Convert_v1beta1_AdditionalUserData_To_v1beta2_AdditionalUserData(in *AdditionalUserData, out *v1beta2.AdditionalUserData, s conversion.Scope) error {
	return autoConvert_v1beta1_AdditionalUserData_To_v1beta2_AdditionalUserData(in, out, s)
}

func autoConvert_v1beta2_AdditionalUserData_To_v1beta1_AdditionalUserData(in *v1beta2.AdditionalUserData, out *AdditionalUserData, s conversion.Scope) error {
	out.Config = in.Config
	out.Data = *(*map[string]string)(unsafe.Pointer(&in.Data))
	out.Strict = in.Strict
	return nil
}

// Convert_v1beta2_AdditionalUserData_To_v1beta1_AdditionalUserData is an autogenerated conversion function.
func Convert_v1beta2_AdditionalUserData_To_v1beta1_AdditionalUserData(in *v1beta2.AdditionalUserData, out *AdditionalUserData, s conversion.Scope) error {
	return autoConvert_v1beta2_AdditionalUserData_To_v1beta1_AdditionalUserData(in, out, s)
}

func autoConvert_v1beta1_ComponentConfig_To_v1beta2_ComponentConfig(in *ComponentConfig, out *v1beta2.ComponentConfig, s conversion.Scope) error {
	out.ExtraEnv = *(*map[string]string)(unsafe.Pointer(&in.ExtraEnv))
	out.ExtraArgs = *(*[]string)(unsafe.Pointer(&in.ExtraArgs))
	out.ExtraMounts = *(*map[string]string)(unsafe.Pointer(&in.ExtraMounts))
	out.OverrideImage = in.OverrideImage
	return nil
}

// Convert_v1beta1_ComponentConfig_To_v1beta2_ComponentConfig is an autogenerated conversion function.
func Convert_v1beta1_ComponentConfig_To_v1beta2_ComponentConfig(in *ComponentConfig, out *v1beta2.ComponentConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_ComponentConfig_To_v1beta2_ComponentConfig(in, out, s)
}

func autoConvert_v1beta2_ComponentConfig_To_v1beta1_ComponentConfig(in *v1beta2.ComponentConfig, out *ComponentConfig, s conversion.Scope) error {
	out.ExtraEnv = *(*map[string]string)(unsafe.Pointer(&in.ExtraEnv))
	out.ExtraArgs = *(*[]string)(unsafe.Pointer(&in.ExtraArgs))
	out.ExtraMounts = *(*map[string]string)(unsafe.Pointer(&in.ExtraMounts))
	out.OverrideImage = in.OverrideImage
	return nil
}

// Convert_v1beta2_ComponentConfig_To_v1beta1_ComponentConfig is an autogenerated conversion function.
func Convert_v1beta2_ComponentConfig_To_v1beta1_ComponentConfig(in *v1beta2.ComponentConfig, out *ComponentConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_ComponentConfig_To_v1beta1_ComponentConfig(in, out, s)
}

func autoConvert_v1beta1_File_To_v1beta2_File(in *File, out *v1beta2.File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = v1beta2.Encoding(in.Encoding)
	out.Content = in.Content
	out.ContentFrom = (*v1beta2.FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1beta1_File_To_v1beta2_File is an autogenerated conversion function.
func Convert_v1beta1_File_To_v1beta2_File(in *File, out *v1beta2.File, s conversion.Scope) error {
	return autoConvert_v1beta1_File_To_v1beta2_File(in, out, s)
}

func autoConvert_v1beta2_File_To_v1beta1_File(in *v1beta2.File, out *File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = Encoding(in.Encoding)
	out.Content = in.Content
	out.ContentFrom = (*FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1beta2_File_To_v1beta1_File is an autogenerated conversion function.
func Convert_v1beta2_File_To_v1beta1_File(in *v1beta2.File, out *File, s conversion.Scope) error {
	return autoConvert_v1beta2_File_To_v1beta1_File(in, out, s)
}

func autoConvert_v1beta1_FileSource_To_v1beta2_FileSource(in *FileSource, out *v1beta2.FileSource, s conversion.Scope) error {
	out.Secret = (*v1beta2.FileSourceRef)(unsafe.Pointer(in.Secret))
	out.ConfigMap = (*v1beta2.FileSourceRef)(unsafe.Pointer(in.ConfigMap))
	return nil
}

// Convert_v1beta1_FileSource_To_v1beta2_FileSource is an autogenerated conversion function.
func Convert_v1beta1_FileSource_To_v1beta2_FileSource(in *FileSource, out *v1beta2.FileSource, s conversion.Scope) error {
	return autoConvert_v1beta1_FileSource_To_v1beta2_FileSource(in, out, s)
}

func autoConvert_v1beta2_FileSource_To_v1beta1_FileSource(in *v1beta2.FileSource, out *FileSource, s conversion.Scope) error {
	out.Secret = (*FileSourceRef)(unsafe.Pointer(in.Secret))
	out.ConfigMap = (*FileSourceRef)(unsafe.Pointer(in.ConfigMap))
	return nil
}

// Convert_v1beta2_FileSource_To_v1beta1_FileSource is an autogenerated conversion function.
func Convert_v1beta2_FileSource_To_v1beta1_FileSource(in *v1beta2.FileSource, out *FileSource, s conversion.Scope) error {
	return autoConvert_v1beta2_FileSource_To_v1beta1_FileSource(in, out, s)
}

func autoConvert_v1beta1_FileSourceRef_To_v1beta2_FileSourceRef(in *FileSourceRef, out *v1beta2.FileSourceRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_FileSourceRef_To_v1beta2_FileSourceRef is an autogenerated conversion function.
func Convert_v1beta1_FileSourceRef_To_v1beta2_FileSourceRef(in *FileSourceRef, out *v1beta2.FileSourceRef, s conversion.Scope) error {
	return autoConvert_v1beta1_FileSourceRef_To_v1beta2_FileSourceRef(in, out, s)
}

func autoConvert_v1beta2_FileSourceRef_To_v1beta1_FileSourceRef(in *v1beta2.FileSourceRef, out *FileSourceRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta2_FileSourceRef_To_v1beta1_FileSourceRef is an autogenerated conversion function.
func Convert_v1beta2_FileSourceRef_To_v1beta1_FileSourceRef(in *v1beta2.FileSourceRef, out *FileSourceRef, s conversion.Scope) error {
	return autoConvert_v1beta2_FileSourceRef_To_v1beta1_FileSourceRef(in, out, s)
}

func autoConvert_v1beta1_Mirror_To_v1beta2_Mirror(in *Mirror, out *v1beta2.Mirror, s conversion.Scope) error {
	out.Endpoint = *(*[]string)(unsafe.Pointer(&in.Endpoint))
	out.Rewrite = *(*map[string]string)(unsafe.Pointer(&in.Rewrite))
	return nil
}

// Convert_v1beta1_Mirror_To_v1beta2_Mirror is an autogenerated conversion function.
func Convert_v1beta1_Mirror_To_v1beta2_Mirror(in *Mirror, out *v1beta2.Mirror, s conversion.Scope) error {
	return autoConvert_v1beta1_Mirror_To_v1beta2_Mirror(in, out, s)
}

func autoConvert_v1beta2_Mirror_To_v1beta1_Mirror(in *v1beta2.Mirror, out *Mirror, s conversion.Scope) error {
	out.Endpoint = *(*[]string)(unsafe.Pointer(&in.Endpoint))
	out.Rewrite = *(*map[string]string)(unsafe.Pointer(&in.Rewrite))
	return nil
}

// Convert_v1beta2_Mirror_To_v1beta1_Mirror is an autogenerated conversion function.
func Convert_v1beta2_Mirror_To_v1beta1_Mirror(in *v1beta2.Mirror, out *Mirror, s conversion.Scope) error {
	return autoConvert_v1beta2_Mirror_To_v1beta1_Mirror(in, out, s)
}

func autoConvert_v1beta1_NTP_To_v1beta2_NTP(in *NTP, out *v1beta2.NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta1_NTP_To_v1beta2_NTP is an autogenerated conversion function.
func Convert_v1beta1_NTP_To_v1beta2_NTP(in *NTP, out *v1beta2.NTP, s conversion.Scope) error {
	return autoConvert_v1beta1_NTP_To_v1beta2_NTP(in, out, s)
}

func autoConvert_v1beta2_NTP_To_v1beta1_NTP(in *v1beta2.NTP, out *NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta2_NTP_To_v1beta1_NTP is an autogenerated conversion function.
func Convert_v1beta2_NTP_To_v1beta1_NTP(in *v1beta2.NTP, out *NTP, s conversion.Scope) error {
	return autoConvert_v1beta2_NTP_To_v1beta1_NTP(in, out, s)
}

func autoConvert_v1beta1_RKE2AgentConfig_To_v1beta2_RKE2AgentConfig(in *RKE2AgentConfig, out *v1beta2.RKE2AgentConfig, s conversion.Scope) error {
	out.DataDir = in.DataDir
	out.NodeLabels = *(*[]string)(unsafe.Pointer(&in.NodeLabels))
	out.NodeAnnotations = *(*map[string]string)(unsafe.Pointer(&in.NodeAnnotations))
	out.NodeTaints = *(*[]string)(unsafe.Pointer(&in.NodeTaints))
	out.NodeNamePrefix = in.NodeNamePrefix
	out.NTP = (*v1beta2.NTP)(unsafe.Pointer(in.NTP))
	out.ImageCredentialProviderConfigMap = (*corev1.ObjectReference)(unsafe.Pointer(in.ImageCredentialProviderConfigMap))
	out.ContainerRuntimeEndpoint = in.ContainerRuntimeEndpoint
	out.Snapshotter = in.Snapshotter
	out.CISProfile = v1beta2.CISProfile(in.CISProfile)
	out.PodSecurityAdmissionConfigFile = in.PodSecurityAdmissionConfigFile
	out.ResolvConf = (*corev1.ObjectReference)(unsafe.Pointer(in.ResolvConf))
	out.ProtectKernelDefaults = in.ProtectKernelDefaults
	out.SystemDefaultRegistry = in.SystemDefaultRegistry
	out.EnableContainerdSElinux = in.EnableContainerdSElinux
	out.KubeletPath = in.KubeletPath
	out.Kubelet = (*v1beta2.ComponentConfig)(unsafe.Pointer(in.Kubelet))
	out.KubeProxy = (*v1beta2.ComponentConfig)(unsafe.Pointer(in.KubeProxy))
	out.RuntimeImage = in.RuntimeImage
	out.LoadBalancerPort = in.LoadBalancerPort
	out.AirGapped = in.AirGapped
	out.AirGappedChecksum = in.AirGappedChecksum
	out.Format = v1beta2.Format(in.Format)
	if err := Convert_v1beta1_AdditionalUserData_To_v1beta2_AdditionalUserData(&in.AdditionalUserData, &out.AdditionalUserData, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_RKE2AgentConfig_To_v1beta1_RKE2AgentConfig(in *v1beta2.RKE2AgentConfig, out *RKE2AgentConfig, s conversion.Scope) error {
	out.DataDir = in.DataDir
	out.NodeLabels = *(*[]string)(unsafe.Pointer(&in.NodeLabels))
	out.NodeAnnotations = *(*map[string]string)(unsafe.Pointer(&in.NodeAnnotations))
	out.NodeTaints = *(*[]string)(unsafe.Pointer(&in.NodeTaints))
	out.NodeNamePrefix = in.NodeNamePrefix
	out.NTP = (*NTP)(unsafe.Pointer(in.NTP))
	out.ImageCredentialProviderConfigMap = (*corev1.ObjectReference)(unsafe.Pointer(in.ImageCredentialProviderConfigMap))
	out.ContainerRuntimeEndpoint = in.ContainerRuntimeEndpoint
	out.Snapshotter = in.Snapshotter
	out.CISProfile = CISProfile(in.CISProfile)
	out.PodSecurityAdmissionConfigFile = in.PodSecurityAdmissionConfigFile
	out.ResolvConf = (*corev1.ObjectReference)(unsafe.Pointer(in.ResolvConf))
	out.ProtectKernelDefaults = in.ProtectKernelDefaults
	out.SystemDefaultRegistry = in.SystemDefaultRegistry
	out.EnableContainerdSElinux = in.EnableContainerdSElinux
	out.KubeletPath = in.KubeletPath
	out.Kubelet = (*ComponentConfig)(unsafe.Pointer(in.Kubelet))
	out.KubeProxy = (*ComponentConfig)(unsafe.Pointer(in.KubeProxy))
	out.RuntimeImage = in.RuntimeImage
	out.LoadBalancerPort = in.LoadBalancerPort
	out.AirGapped = in.AirGapped
	out.AirGappedChecksum = in.AirGappedChecksum
	out.Format = Format(in.Format)
	if err := Convert_v1beta2_AdditionalUserData_To_v1beta1_AdditionalUserData(&in.AdditionalUserData, &out.AdditionalUserData, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_RKE2Config_To_v1beta2_RKE2Config(in *RKE2Config, out *v1beta2.RKE2Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RKE2ConfigSpec_To_v1beta2_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RKE2ConfigStatus_To_v1beta2_RKE2ConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2Config_To_v1beta2_RKE2Config is an autogenerated conversion function.
func Convert_v1beta1_RKE2Config_To_v1beta2_RKE2Config(in *RKE2Config, out *v1beta2.RKE2Config, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2Config_To_v1beta2_RKE2Config(in, out, s)
}

func autoConvert_v1beta2_RKE2Config_To_v1beta1_RKE2Config(in *v1beta2.RKE2Config, out *RKE2Config, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_RKE2ConfigSpec_To_v1beta1_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_RKE2ConfigStatus_To_v1beta1_RKE2ConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2Config_To_v1beta1_RKE2Config is an autogenerated conversion function.
func Convert_v1beta2_RKE2Config_To_v1beta1_RKE2Config(in *v1beta2.RKE2Config, out *RKE2Config, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2Config_To_v1beta1_RKE2Config(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigCustomDefaulter_To_v1beta2_RKE2ConfigCustomDefaulter(in *RKE2ConfigCustomDefaulter, out *v1beta2.RKE2ConfigCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ConfigCustomDefaulter_To_v1beta2_RKE2ConfigCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigCustomDefaulter_To_v1beta2_RKE2ConfigCustomDefaulter(in *RKE2ConfigCustomDefaulter, out *v1beta2.RKE2ConfigCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigCustomDefaulter_To_v1beta2_RKE2ConfigCustomDefaulter(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigCustomDefaulter_To_v1beta1_RKE2ConfigCustomDefaulter(in *v1beta2.RKE2ConfigCustomDefaulter, out *RKE2ConfigCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ConfigCustomDefaulter_To_v1beta1_RKE2ConfigCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigCustomDefaulter_To_v1beta1_RKE2ConfigCustomDefaulter(in *v1beta2.RKE2ConfigCustomDefaulter, out *RKE2ConfigCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigCustomDefaulter_To_v1beta1_RKE2ConfigCustomDefaulter(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigCustomValidator_To_v1beta2_RKE2ConfigCustomValidator(in *RKE2ConfigCustomValidator, out *v1beta2.RKE2ConfigCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ConfigCustomValidator_To_v1beta2_RKE2ConfigCustomValidator is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigCustomValidator_To_v1beta2_RKE2ConfigCustomValidator(in *RKE2ConfigCustomValidator, out *v1beta2.RKE2ConfigCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigCustomValidator_To_v1beta2_RKE2ConfigCustomValidator(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigCustomValidator_To_v1beta1_RKE2ConfigCustomValidator(in *v1beta2.RKE2ConfigCustomValidator, out *RKE2ConfigCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ConfigCustomValidator_To_v1beta1_RKE2ConfigCustomValidator is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigCustomValidator_To_v1beta1_RKE2ConfigCustomValidator(in *v1beta2.RKE2ConfigCustomValidator, out *RKE2ConfigCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigCustomValidator_To_v1beta1_RKE2ConfigCustomValidator(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigList_To_v1beta2_RKE2ConfigList(in *RKE2ConfigList, out *v1beta2.RKE2ConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.RKE2Config, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_RKE2Config_To_v1beta2_RKE2Config(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RKE2ConfigList_To_v1beta2_RKE2ConfigList is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigList_To_v1beta2_RKE2ConfigList(in *RKE2ConfigList, out *v1beta2.RKE2ConfigList, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigList_To_v1beta2_RKE2ConfigList(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigList_To_v1beta1_RKE2ConfigList(in *v1beta2.RKE2ConfigList, out *RKE2ConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RKE2Config, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_RKE2Config_To_v1beta1_RKE2Config(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_RKE2ConfigList_To_v1beta1_RKE2ConfigList is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigList_To_v1beta1_RKE2ConfigList(in *v1beta2.RKE2ConfigList, out *RKE2ConfigList, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigList_To_v1beta1_RKE2ConfigList(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigSpec_To_v1beta2_RKE2ConfigSpec(in *RKE2ConfigSpec, out *v1beta2.RKE2ConfigSpec, s conversion.Scope) error {
	out.Files = *(*[]v1beta2.File)(unsafe.Pointer(&in.Files))
	out.PreRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PreRKE2Commands))
	out.PostRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PostRKE2Commands))
	if err := Convert_v1beta1_RKE2AgentConfig_To_v1beta2_RKE2AgentConfig(&in.AgentConfig, &out.AgentConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Registry_To_v1beta2_Registry(&in.PrivateRegistriesConfig, &out.PrivateRegistriesConfig, s); err != nil {
		return err
	}
	out.GzipUserData = (*bool)(unsafe.Pointer(in.GzipUserData))
	return nil
}

func autoConvert_v1beta2_RKE2ConfigSpec_To_v1beta1_RKE2ConfigSpec(in *v1beta2.RKE2ConfigSpec, out *RKE2ConfigSpec, s conversion.Scope) error {
	out.Files = *(*[]File)(unsafe.Pointer(&in.Files))
	out.PreRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PreRKE2Commands))
	out.PostRKE2Commands = *(*[]string)(unsafe.Pointer(&in.PostRKE2Commands))
	if err := Convert_v1beta2_RKE2AgentConfig_To_v1beta1_RKE2AgentConfig(&in.AgentConfig, &out.AgentConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_Registry_To_v1beta1_Registry(&in.PrivateRegistriesConfig, &out.PrivateRegistriesConfig, s); err != nil {
		return err
	}
	out.GzipUserData = (*bool)(unsafe.Pointer(in.GzipUserData))
	return nil
}

func autoConvert_v1beta1_RKE2ConfigStatus_To_v1beta2_RKE2ConfigStatus(in *RKE2ConfigStatus, out *v1beta2.RKE2ConfigStatus, s conversion.Scope) error {
	// WARNING: in.Ready requires manual conversion: does not exist in peer-type
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.V1Beta2 requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_RKE2ConfigStatus_To_v1beta1_RKE2ConfigStatus(in *v1beta2.RKE2ConfigStatus, out *RKE2ConfigStatus, s conversion.Scope) error {
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.Initialization requires manual conversion: does not exist in peer-type
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.ObservedGeneration = in.ObservedGeneration
	// WARNING: in.Deprecated requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_RKE2ConfigTemplate_To_v1beta2_RKE2ConfigTemplate(in *RKE2ConfigTemplate, out *v1beta2.RKE2ConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RKE2ConfigTemplateSpec_To_v1beta2_RKE2ConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2ConfigTemplate_To_v1beta2_RKE2ConfigTemplate is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigTemplate_To_v1beta2_RKE2ConfigTemplate(in *RKE2ConfigTemplate, out *v1beta2.RKE2ConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigTemplate_To_v1beta2_RKE2ConfigTemplate(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigTemplate_To_v1beta1_RKE2ConfigTemplate(in *v1beta2.RKE2ConfigTemplate, out *RKE2ConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_RKE2ConfigTemplateSpec_To_v1beta1_RKE2ConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ConfigTemplate_To_v1beta1_RKE2ConfigTemplate is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigTemplate_To_v1beta1_RKE2ConfigTemplate(in *v1beta2.RKE2ConfigTemplate, out *RKE2ConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigTemplate_To_v1beta1_RKE2ConfigTemplate(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigTemplateCustomDefaulter_To_v1beta2_RKE2ConfigTemplateCustomDefaulter(in *RKE2ConfigTemplateCustomDefaulter, out *v1beta2.RKE2ConfigTemplateCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ConfigTemplateCustomDefaulter_To_v1beta2_RKE2ConfigTemplateCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigTemplateCustomDefaulter_To_v1beta2_RKE2ConfigTemplateCustomDefaulter(in *RKE2ConfigTemplateCustomDefaulter, out *v1beta2.RKE2ConfigTemplateCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigTemplateCustomDefaulter_To_v1beta2_RKE2ConfigTemplateCustomDefaulter(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigTemplateCustomDefaulter_To_v1beta1_RKE2ConfigTemplateCustomDefaulter(in *v1beta2.RKE2ConfigTemplateCustomDefaulter, out *RKE2ConfigTemplateCustomDefaulter, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ConfigTemplateCustomDefaulter_To_v1beta1_RKE2ConfigTemplateCustomDefaulter is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigTemplateCustomDefaulter_To_v1beta1_RKE2ConfigTemplateCustomDefaulter(in *v1beta2.RKE2ConfigTemplateCustomDefaulter, out *RKE2ConfigTemplateCustomDefaulter, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigTemplateCustomDefaulter_To_v1beta1_RKE2ConfigTemplateCustomDefaulter(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigTemplateCustomValidator_To_v1beta2_RKE2ConfigTemplateCustomValidator(in *RKE2ConfigTemplateCustomValidator, out *v1beta2.RKE2ConfigTemplateCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_RKE2ConfigTemplateCustomValidator_To_v1beta2_RKE2ConfigTemplateCustomValidator is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigTemplateCustomValidator_To_v1beta2_RKE2ConfigTemplateCustomValidator(in *RKE2ConfigTemplateCustomValidator, out *v1beta2.RKE2ConfigTemplateCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigTemplateCustomValidator_To_v1beta2_RKE2ConfigTemplateCustomValidator(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigTemplateCustomValidator_To_v1beta1_RKE2ConfigTemplateCustomValidator(in *v1beta2.RKE2ConfigTemplateCustomValidator, out *RKE2ConfigTemplateCustomValidator, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RKE2ConfigTemplateCustomValidator_To_v1beta1_RKE2ConfigTemplateCustomValidator is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigTemplateCustomValidator_To_v1beta1_RKE2ConfigTemplateCustomValidator(in *v1beta2.RKE2ConfigTemplateCustomValidator, out *RKE2ConfigTemplateCustomValidator, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigTemplateCustomValidator_To_v1beta1_RKE2ConfigTemplateCustomValidator(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigTemplateList_To_v1beta2_RKE2ConfigTemplateList(in *RKE2ConfigTemplateList, out *v1beta2.RKE2ConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.RKE2ConfigTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_RKE2ConfigTemplate_To_v1beta2_RKE2ConfigTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RKE2ConfigTemplateList_To_v1beta2_RKE2ConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigTemplateList_To_v1beta2_RKE2ConfigTemplateList(in *RKE2ConfigTemplateList, out *v1beta2.RKE2ConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigTemplateList_To_v1beta2_RKE2ConfigTemplateList(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigTemplateList_To_v1beta1_RKE2ConfigTemplateList(in *v1beta2.RKE2ConfigTemplateList, out *RKE2ConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RKE2ConfigTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_RKE2ConfigTemplate_To_v1beta1_RKE2ConfigTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_RKE2ConfigTemplateList_To_v1beta1_RKE2ConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigTemplateList_To_v1beta1_RKE2ConfigTemplateList(in *v1beta2.RKE2ConfigTemplateList, out *RKE2ConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigTemplateList_To_v1beta1_RKE2ConfigTemplateList(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigTemplateResource_To_v1beta2_RKE2ConfigTemplateResource(in *RKE2ConfigTemplateResource, out *v1beta2.RKE2ConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_RKE2ConfigSpec_To_v1beta2_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2ConfigTemplateResource_To_v1beta2_RKE2ConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigTemplateResource_To_v1beta2_RKE2ConfigTemplateResource(in *RKE2ConfigTemplateResource, out *v1beta2.RKE2ConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigTemplateResource_To_v1beta2_RKE2ConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigTemplateResource_To_v1beta1_RKE2ConfigTemplateResource(in *v1beta2.RKE2ConfigTemplateResource, out *RKE2ConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_RKE2ConfigSpec_To_v1beta1_RKE2ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ConfigTemplateResource_To_v1beta1_RKE2ConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigTemplateResource_To_v1beta1_RKE2ConfigTemplateResource(in *v1beta2.RKE2ConfigTemplateResource, out *RKE2ConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigTemplateResource_To_v1beta1_RKE2ConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta1_RKE2ConfigTemplateSpec_To_v1beta2_RKE2ConfigTemplateSpec(in *RKE2ConfigTemplateSpec, out *v1beta2.RKE2ConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_RKE2ConfigTemplateResource_To_v1beta2_RKE2ConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RKE2ConfigTemplateSpec_To_v1beta2_RKE2ConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_RKE2ConfigTemplateSpec_To_v1beta2_RKE2ConfigTemplateSpec(in *RKE2ConfigTemplateSpec, out *v1beta2.RKE2ConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RKE2ConfigTemplateSpec_To_v1beta2_RKE2ConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_RKE2ConfigTemplateSpec_To_v1beta1_RKE2ConfigTemplateSpec(in *v1beta2.RKE2ConfigTemplateSpec, out *RKE2ConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_RKE2ConfigTemplateResource_To_v1beta1_RKE2ConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RKE2ConfigTemplateSpec_To_v1beta1_RKE2ConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_RKE2ConfigTemplateSpec_To_v1beta1_RKE2ConfigTemplateSpec(in *v1beta2.RKE2ConfigTemplateSpec, out *RKE2ConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_RKE2ConfigTemplateSpec_To_v1beta1_RKE2ConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_Registry_To_v1beta2_Registry(in *Registry, out *v1beta2.Registry, s conversion.Scope) error {
	out.Mirrors = *(*map[string]v1beta2.Mirror)(unsafe.Pointer(&in.Mirrors))
	out.Configs = *(*map[string]v1beta2.RegistryConfig)(unsafe.Pointer(&in.Configs))
	return nil
}

// Convert_v1beta1_Registry_To_v1beta2_Registry is an autogenerated conversion function.
func Convert_v1beta1_Registry_To_v1beta2_Registry(in *Registry, out *v1beta2.Registry, s conversion.Scope) error {
	return autoConvert_v1beta1_Registry_To_v1beta2_Registry(in, out, s)
}

func autoConvert_v1beta2_Registry_To_v1beta1_Registry(in *v1beta2.Registry, out *Registry, s conversion.Scope) error {
	out.Mirrors = *(*map[string]Mirror)(unsafe.Pointer(&in.Mirrors))
	out.Configs = *(*map[string]RegistryConfig)(unsafe.Pointer(&in.Configs))
	return nil
}

// Convert_v1beta2_Registry_To_v1beta1_Registry is an autogenerated conversion function.
func Convert_v1beta2_Registry_To_v1beta1_Registry(in *v1beta2.Registry, out *Registry, s conversion.Scope) error {
	return autoConvert_v1beta2_Registry_To_v1beta1_Registry(in, out, s)
}

func autoConvert_v1beta1_RegistryConfig_To_v1beta2_RegistryConfig(in *RegistryConfig, out *v1beta2.RegistryConfig, s conversion.Scope) error {
	out.AuthSecret = in.AuthSecret
	if err := Convert_v1beta1_TLSConfig_To_v1beta2_TLSConfig(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RegistryConfig_To_v1beta2_RegistryConfig is an autogenerated conversion function.
func Convert_v1beta1_RegistryConfig_To_v1beta2_RegistryConfig(in *RegistryConfig, out *v1beta2.RegistryConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_RegistryConfig_To_v1beta2_RegistryConfig(in, out, s)
}

func autoConvert_v1beta2_RegistryConfig_To_v1beta1_RegistryConfig(in *v1beta2.RegistryConfig, out *RegistryConfig, s conversion.Scope) error {
	out.AuthSecret = in.AuthSecret
	if err := Convert_v1beta2_TLSConfig_To_v1beta1_TLSConfig(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RegistryConfig_To_v1beta1_RegistryConfig is an autogenerated conversion function.
func Convert_v1beta2_RegistryConfig_To_v1beta1_RegistryConfig(in *v1beta2.RegistryConfig, out *RegistryConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_RegistryConfig_To_v1beta1_RegistryConfig(in, out, s)
}

func autoConvert_v1beta1_TLSConfig_To_v1beta2_TLSConfig(in *TLSConfig, out *v1beta2.TLSConfig, s conversion.Scope) error {
	out.TLSConfigSecret = in.TLSConfigSecret
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1beta1_TLSConfig_To_v1beta2_TLSConfig is an autogenerated conversion function.
func Convert_v1beta1_TLSConfig_To_v1beta2_TLSConfig(in *TLSConfig, out *v1beta2.TLSConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_TLSConfig_To_v1beta2_TLSConfig(in, out, s)
}

func autoConvert_v1beta2_TLSConfig_To_v1beta1_TLSConfig(in *v1beta2.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	out.TLSConfigSecret = in.TLSConfigSecret
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1beta2_TLSConfig_To_v1beta1_TLSConfig is an autogenerated conversion function.
func Convert_v1beta2_TLSConfig_To_v1beta1_TLSConfig(in *v1beta2.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_TLSConfig_To_v1beta1_TLSConfig(in, out, s)
}
