name: run ci checks

on: [pull_request, workflow_dispatch, merge_group]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Verify
        run: make verify
      - name: Build
        run: make managers
      - name: Test
        run: make test
