name: run ci checks

on: [pull_request, workflow_dispatch, merge_group]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Verify
        run: make verify
      - name: Build
        run: make managers
      - name: Test
        run: make test
