name: E2E tests
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: runs-on,runner=4cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Setup kind
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          install_only: true
      - name: Run E2E tests
        run: make test-e2e
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: e2e-artifacts
          path: _artifacts
          if-no-files-found: ignore
  e2e-tests-upgrade:
    runs-on: runs-on,runner=4cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Setup kind
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          install_only: true
      - name: Run E2E tests
        env:
          GINKGO_LABEL_FILTER: upgrade
        run: make test-e2e
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: e2e-upgrade-artifacts
          path: _artifacts
          if-no-files-found: ignore
